      SUBROUTINE ABET(I)
C    SELECTS INITIALLY ACTIVE ALPHABET FROM RANGE (1-MAXBET)
C    MAXBET IS NUMBER OF SIMULTANEOUSLY IN-CORE ALPHABETS
C    DIMFILM CURRENTLY SUPPORTS MAXBET UP TO A MAXIMUM OF 3
      PARAMETER (MAXBET=3)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'ABET'
      IF (I.LT.1.OR.I.GT.MAXBET) GO TO 1
      IBET = I
  999 NTH = .FALSE.
      ROUTIN = STARS6
      RETURN
    1 IF (ICHECK.GT.0) WRITE(ERRREC,10) I,IBET
      CALL DFX130(0)
   10 FORMAT(1H0,'**DIMFILM WARNING**  ROUTINE ABET REFERENCED WITH OUT
     1OF RANGE PARAMETER ',I3/1H ,21X,'EXISTING VALUE ',I3,' RETAINED')
      GO TO 999
      END
