      BLOCK DATA DFXB00
      INCLUDE 'params.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcaa.cmn'
      INCLUDE 'dfxcba.cmn'
      INCLUDE 'dfxcad.cmn'
      INCLUDE 'dfxc16.cmn'
      INCLUDE 'dfxc17.cmn'
C
C    DIMFILM VERSION IS OF FORM NN.NA (WITHOUT LEADING BLANKS)
C
      DATA VERSN/'0.1A '/
C
C    ROUTIN MUST BE INITIALISED TO DASH6 - AND RESET ON TERMINATION
C
      DATA ROUTIN/'------'/
      DATA DASH6/'------'/
      DATA STARS6/'******'/
      DATA SYSTEM/'*******'/
C
      DATA USEFLG/' '/
C    IF USEFLG IS BLANK THEN USER FIELD WILL BE
C    SUPPLIED FROM SYSTEM IF POSSIBLE
C    ELSE A USER REFERENCE WILL BE TAKEN FROM FIELD USER
C    (UP TO 20 CHARACTERS) AND USED BY APPROPRIATE
C    DEVICES.  ROUTINE USEREF MAY BE USED TO SET THIS.
C
      DATA ERRREC/6*'*'/
      DATA IEFILE/-1/
      DATA GKSOS/0/
      DATA WSAC/MSOPWS*.FALSE./
      DATA WSOP/MSOPWS*.FALSE./
C    PRESET BLANKING TO AVOID FORTRAN OPTIMISATION ERRORS
      DATA XBB1,XBB2,YBB1,YBB2/4*0.0/
C    PRESET TV TO RGB CONVERSIONS
      DATA TVRGB/
     1   1.00 , 1.00 , 1.00 , 0.95 ,-0.28 ,-1.11 , 0.62 ,-0.64 ,1.73 ,
     2   1.000, 1.000, 1.000, 0.000,-0.394, 2.020, 0.140,-0.581, 0.000,
     3   9*0.0/
      DATA RGBTV/
     1   0.30 , 0.60 , 0.21 , 0.59 ,-0.28 ,-0.52 , 0.11 ,-0.32 , 0.31 ,
     2   0.299,-0.148, 5.007,0.587,-0.291,-4.193, 0.114, 0.439,-0.814,
     3   9*0.0/
C    PRESET LUT - SPECIFICALLY NEEDED FOR PACKAGE INTERFACE WHEN
C                 DFX162 DUMMIED
      DATA RGBLUT/768*0.0/
C    PRESET NUMWRN AND ICHECK FOR BENEFIT OF ROUTINES ACCESSED
C    PRIOR TO DIMFILM INITIALISATION
      DATA ICHECK,NUMWRN/+2,0/
C    PRESET USE TAPE FLAGS
      DATA UTFLAG/MSOPWS*0/
C NG- OTHER THINGS THAT LOOK LIKE THEY REALLY OUGHT TO BE INITIALIZED.
      DATA X0T/0.0/, Y0T/0.0/
      DATA XTB1/0.0/, XTB2/0.0/, YTB1/0.0/, YTB2/0.0/
      DATA SCALE/0.0/, SCALE1/0.0/
      DATA LINSYM/0/, ISAVE/0/, INTCH/0/, IICHAR/0/
      END
C
C----------------------------------------------
C
