      SUBROUTINE CELAR1(PX,QX,QY,PY,DIMX,DIMY,NCS,NRS,DX,DY,COLIA)
      INTEGER DIMX,DIMY
      INTEGER COLIA(DIMX,DIMY),DX,DY
      CHARACTER*14 C
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcp0.cmn'
      INCLUDE 'dfxcd0.cmn'
      INCLUDE 'dfxcd0s.cmn'
      ROUTIN = 'CELAR1'
      C = 'OVERALL ARRAY'
      I1 = DIMX
      I2 = DIMY
      IF ((I1.LE.0).OR.(I2.LE.0)) GO TO 14
      C = 'CELL SUB-ARRAY'
      I1 = DX
      I2 = DY
      IF ((I1.LE.0).OR.(I2.LE.0)) GO TO 14
      IF ((NCS.LE.0).OR.(NCS.GT.DIMX).OR.(NRS.LE.0).OR.(NRS.GT.DIMY))
     1                            GO TO 12
      IF (((NCS-1+DX).GT.DIMX).OR.((NRS-1+DY).GT.DIMY)) GO TO 10
      CALL DFX170(PX,PY,QX,QY,IERR)
      IF (IERR.NE.0) GO TO 99
      IPAR(1) = DIMX
      IPAR(2) = DIMY
      IPAR(3) = NCS - 1
      IPAR(4) = NRS - 1
      IPAR(5) = DX
      IPAR(6) = DY
C    FLAG AS CELL ARRAY
      NPAR = 0
C    FLAG AS LOOK-UP-TABLE REFERENCES
      LPAR(3) = .TRUE.
C    INPUT RASTER IS COLOUR
      LPAR(4) = .TRUE.
      CALL DFX000(10,ZDUMMY,ZDUMMY,ZDUMMY,COLIA)
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
   99 CONTINUE
      ROUTIN = STARS6
      RETURN
   10 IF (ICHECK.GT.0) WRITE(ERRREC,11) DX,DY,NCS,NRS,DIMX,DIMY
      CALL DFX130(0)
   11 FORMAT(1H0,'**DIMFILM WARNING** CELAR1 REFERENCED WITH INCOMPATIBL
     1E PARAMETERS -'/
     2 1H0,21X,'CELL SUB-ARRAY (',I6,',',I6,') FOR START POSITION (',
     3 I6,',',I6,')'/
     4 1H0,21X,'NOT FULLY WITHIN OVERALL ARRAY (',I6,',',I6,')'/
     5 1H0,21X,'CALL IGNORED')
      GO TO 99
   12 IF (ICHECK.GT.0) WRITE(ERRREC,13) NCS,NRS,DIMX,DIMY
      CALL DFX130(0)
   13 FORMAT(1H0,'**DIMFILM WARNING** CELAR1 REFERENCED WITH INVALID STA
     1RT POSITION (',I6,',',I6,')'/
     2 1H0,21X,'NOT WITHIN OVERALL ARRAY (',I6,',',I6,')'/
     3 1H0,21X,'CALL IGNORED')
      GO TO 99
   14 IF (ICHECK.GT.0) WRITE(ERRREC,15) I1,I2,C
      CALL DFX130(0)
   15 FORMAT(1H0,'**DIMFILM WARNING** CELAR1 REFERENCED WITH INVALID DIM
     1ENSIONS (',I6,',',I6,') FOR ',A/
     2 1H0,21X,'CALL IGNORED')
      GO TO 99
      END
C
C----------------------------------------------
C
