      SUBROUTINE CELMAP(PX,QX,QY,PY,NDX,NDY)
C     PRESETS THE RASTER CELL MAP FOR LINE SCANS
C
C     NOTE: ARGUMENTS CORRESPOND TO (XSTART,XEND,YSTART,YEND,..)
C           GKS CONVENTION DEFINES THE RECTANGLE VIA COORDINATE
C           PAIRS - THUS (PX,PY,QX,QY,...)
C           THE NOTATION PX/Y,QX/Y IS USED FOR CONVENIENCE
C           BUT THE DIMFILM ORDER SHOULD BE NOTED
C           (THIS IS MORE LOGICAL IN THE CONTEXT OF A RASTER IMAGE)
C
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxc24.cmn'
      ROUTIN = 'CELMAP'
      RSTERR = 0
      RASTPX = PX
      RASTPY = PY
      RASTQX = QX
      RASTQY = QY
      RASTDX = NDX
      RASTDY = NDY
C   NOW CHECK FOR VALIDITY
      IF ((RASTPX.EQ.RASTQX).OR.(RASTPY.EQ.RASTQY)) GO TO 10
      IF ((RASTDX.LE.0).OR.(RASTDY.LE.0)) GO TO 12
      RASTLN = 0
   99 CONTINUE
      ROUTIN = STARS6
      RETURN
   10 IF (ICHECK.GT.0) WRITE(ERRREC,11) RASTPX,RASTPY,RASTQX,RASTQY,NDX,
     1                                  NDY
   11 FORMAT(1H0,'**DIMFILM WARNING**  CELMAP DEFINED INVALID AREA (ZERO
     1 RANGE IN AT LEAST ONE DIRECTION); REFERENCED WITH - '/
     2 1H0,21X,1P4E16.8,2I10/1H0,21X,'SUBSEQUENT CELL LINE SCANS WILL BE
     3 DISABLED')
      CALL DFX130(0)
      RASTDX = 0
      GO TO 99
   12 IF (ICHECK.GT.0) WRITE(ERRREC,13) RASTPX,RASTPY,RASTQX,RASTQY,NDX,
     1                                  NDY
   13 FORMAT(1H0,'**DIMFILM WARNING**  CELMAP DEFINED INVALID CELL DIVIS
     1IONS IN AT LEAST ONE DIRECTION; REFERENCED WITH - '/
     2 1H0,21X,1P4E16.8,2I10/1H0,21X,'SUBSEQUENT CELL LINE SCANS WILL BE
     3 DISABLED')
      CALL DFX130(0)
      RASTDX = 0
      GO TO 99
      END
C
C----------------------------------------------
C
