      SUBROUTINE CELSCR(COLIA,DX)
C    FOR RUN-LENGTH ENCODING INPUT DATA MUST BE:
C                  COLIA(1,I) = RUN LENGTH
C                  COLIA(2,I) = LUT REFERENCE,  FOR I=1,DX
C    (NOTE THIS WILL EVENTUALLY BE PASSED AS COLIA(2*DX,1))
      INTEGER DX
      INTEGER COLIA(2,DX)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxc24.cmn'
      INCLUDE 'dfxcp0.cmn'
      INCLUDE 'dfxcd0.cmn'
      INCLUDE 'dfxcd0s.cmn'
      ROUTIN = 'CELSCR'
      IF (DX.LE.0) GO TO 10
C    SET DATA LENGTH AS TOTAL COMBINED LENGTH OF DATA PAIRS
      IPAR(1) = 2*DX
      IPAR(2) = 1
      IPAR(3) = 0
      IPAR(4) = 0
      IPAR(5) = RASTDX
      IPAR(6) = RASTDY
C    FLAG AS CELL SCAN LINE
      RASTLN = RASTLN + 1
      NPAR = RASTLN
      IF (RASTLN.GT.RASTDY) GO TO 12
C    FLAG AS LOOK-UP-TABLE REFERENCES
      LPAR(3) = .TRUE.
C    INPUT RASTER IS COLOUR
      LPAR(4) = .TRUE.
C    FLAG AS RUN-LENGTH
      LPAR(5) = .TRUE.
      CALL DFX000(10,ZDUMMY,ZDUMMY,ZDUMMY,COLIA)
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
   99 CONTINUE
      ROUTIN = STARS6
      RETURN
   10 IF (ICHECK.GT.0) WRITE(ERRREC,11) DX
      CALL DFX130(0)
   11 FORMAT(1H0,'**DIMFILM WARNING** CELSCR REFERENCED WITH INVALID ARR
     1AY DIMENSION ',I6/1H0,21X,'CALL IGNORED')
      GO TO 99
   12 IF (RASTLN.GT.(RASTDY+1)) GO TO 99
      IF(ICHECK.GT.0) WRITE(ERRREC,13)
      CALL DFX130(0)
   13 FORMAT(1H0,'**DIMFILM WARNING** CELSCR DETECTED SCAN LINE BEYOND C
     1ELL MAPPED AREA - SUBSEQUENT SCAN LINES WILL BE IGNORED UNTIL RESE
     2T OCCURS')
      GO TO 99
      END
C
C----------------------------------------------
C
