      SUBROUTINE CIRCLE(X0,Y0,R)
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'CIRCLE'
      CALL DFX500(X0,Y0,R,0.,360.,.FALSE.)
C    PARAMETER 5 IGNORED BY DFX500 - DEGREES USED HERE DESCRIPTIVELY
C    LAST PARAMETER (LOGICAL) INDICATES CALL OF DFX500 IS WHOLE CIRCLE
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
      END
