      SUBROUTINE CONTR2(GRID,NX,NY,NCC,CSTART,STP)
      REAL GRID(NX,NY)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc11.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'CONTR2'
      CALL DFX300
      CSTEP = STP
      NC = 1
      VAL = CSTART
      NC1 = NCC
      IF (NX.LE.1.OR.NY.LE.1) GO TO 10
      IF (NC1.EQ.1) CSTEP = 0.0
C    CSTEP NOT USED WHEN SINGLE CONTOUR ONLY IS PLOTTED - ENSURES
C    VALUES WILL BE PRODUCED IF REQUIRED.
      DO 1 K=1,NC1
      CALL DFX404(GRID,NX,NY,NC,VAL)
    1 VAL = VAL + CSTEP
      CALL DFX301
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
   99 CONTINUE
      ROUTIN = STARS6
      RETURN
   10 IF (ICHECK.GT.0) WRITE(ERRREC,11) ROUTIN
   11 FORMAT(1H0,'**DIMFILM WARNING**  CONTOURING ATTEMPTED WITH A GRID
     1DIMENSION LESS THAN 2'/1H ,21X,'CALL OF ',A,'IGNORED')
      CALL DFX130(0)
      GO TO 99
      END
