      SUBROUTINE CONTR1(GRID,NX,NY,NCC,CVALS,ICVALS)
C    ICVALS SELECTS COLOUR/INTENSITY FROM GROUPS 1-3
C    IN THIS ONE INSTANCE VALUES ARE IN SAME COLOUR/INTENSITY
C    AS THE CONTOUR
      REAL GRID(NX,NY),CVALS(NCC)
      INTEGER ICVALS(NCC)
      LOGICAL CSLAB
      INCLUDE 'dfxc11.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc04.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'CONTR1'
      IF (NX.LE.1.OR.NY.LE.1) GO TO 10
      CALL DFX300
      CSTEP = 0.0
      CSLAB = CLAB
      ICOLP1 = ICOLPT(1)
      ICOLP2 = ICOLPT(2)
      NC = 1
      NC1 = NCC
      I1 = 2
      DO 1 K=1,NC1
      J = ICVALS(K)
      IF ((ABS(J).LE.3).AND.(J.NE.0)) GO TO 2
      IF (ICHECK.GT.0) WRITE(ERRREC,12) J,K
   12 FORMAT(1H0,'**DIMFILM WARNING** CONTR1 DETECTED INVALID COLOUR/INT
     1ENSITY GROUP ',I3,' FOR CONTOUR ',I3/1H ,21X,
     2 'GROUP 1 WILL BE USED')
      CALL DFX130(0)
      J = 1
    2 ICOLPT(1) = J
      ICOLPT(2) = J
      CALL DFX147(1)
      CLAB = J.GT.0
      IF (K.NE.1) I1 = K - 1
      A = ABS(CVALS(K)-CVALS(I1))
      IF (K.LT.NC1) A = AMIN1(A,ABS(CVALS(K+1)-CVALS(K)))
      IF (NC1.NE.1) CSTEP = A
C    CSTEP PASSES THE DIFFERENCE BETWEEN PRESENT CONTOUR AND ITS
C    NEAREST NEIGHBOUR
    1 CALL DFX404(GRID,NX,NY,NC,CVALS(K))
      ICOLPT(1) = ICOLP1
      ICOLPT(2) = ICOLP2
      CLAB = CSLAB
      CALL DFX301
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
   99 CONTINUE
      ROUTIN = STARS6
      RETURN
   10 IF (ICHECK.GT.0) WRITE(ERRREC,11) ROUTIN
   11 FORMAT(1H0,'**DIMFILM WARNING**  CONTOURING ATTEMPTED WITH A GRID
     1DIMENSION LESS THAN 2'/1H ,21X,'CALL OF ',A,'IGNORED')
      CALL DFX130(0)
      GO TO 99
      END
C
C----------------------------------------------
C
