      SUBROUTINE DFX005
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
C    JUMP TO DFX009 TO ISSUE DIAGNOSTIC
C
      CALL DFX009
C
      IF (SYSTEM.EQ.'*******') CALL DFX001(ROUTIN,24)
C    IF DIMFILM-SYSTEM (NEED NOT BE PURE DIMFILM) NOT INITIATED
C    ISSUE ERROR 024 AND ABORT
C    N.B. DFX001 ACCESSES DFX009 DIRECT - SO NO RECURSION
      RETURN
      END
