      SUBROUTINE DFX008(NAMEWS,IWS)
C    INTERNAL ROUTINE
C    LOOKS FOR DEVICE 'NAMEWS' AND RETURNS WS
      INCLUDE 'params.cmn'
      INCLUDE 'dfxcad.cmn'
      INCLUDE 'dfxcbf.cmn'
      CHARACTER*(*) NAMEWS
      IWS = 0
      DO 1 I=1,MSOPWS
      IF (NAMEWS.EQ.WSNAME(I)) GO TO 2
    1 CONTINUE
      GO TO 99
C    FLAG AS KNOWN
    2 IWS = I
C    NOW CHECK WS OPEN
C    IF NOT OPEN FLAG AS KNOWN BUT NOT OPEN
      IF (.NOT.WSOP(IWS)) IWS = -IWS
   99 RETURN
      END
