      SUBROUTINE DFX009
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
C    ISSUE DIAGNOSTIC ANYWAY - SEPARATED FROM DFX005 TO AVOID
C    RECURSION WHEN ERROR 024 OCCURS AND DFX001 IS CALLED.
C    DFX001 CALLS DFX009 DIRECTLY.
C    (RECURSION IS NON-CRITICAL BUT ADVERSELY AFFECTS
C     TRACEBACK ON SOME SYSTEMS)
      IF (IEFILE.LT.-1) GO TO 100
      DO 1 I=1,6
      IREC = I
    1 IF (ERRREC(I)(1:1).EQ.'*') GO TO 2
      IREC = 7
    2 IREC = IREC - 1
      IF (IREC.GT.0) THEN
           IF (IEFILE.EQ.-1) THEN
                        WRITE(*,10)(ERRREC(I),I=1,IREC)
           ELSE
                        WRITE(IEFILE,10)( ERRREC(I),I=1,IREC)
           ENDIF
      ENDIF
  100 DO 3 I=1,6
    3 ERRREC(I) = '*'
      RETURN
   10 FORMAT(A120)
      END
