      SUBROUTINE DFX010(INCHAR,UTCHAR,IN,UT,ERR)
C    CHARACTER CONVERSION TO UPPER CASE - OPTIONAL BLANK REMOVAL
C    CHARACTER STRING INCHAR CONVERTED INTO UTCHAR ACCORDING TO -
C    IN = 0    NO BLANK REMOVAL
C         >0   BLANK REMOVAL
C
C    UT IS LENGTH OF RETURNED STRING
C    ERR RETURNS ERROR CONDITION -
C         0    NO ERROR, NO CONVERSION REQUIRED
C         1    INPUT STRING TRUNCATED
C
      CHARACTER*(*) INCHAR,UTCHAR
      CHARACTER*1 C
      CHARACTER*26 LOW,UP
      INTEGER IN,UT,ERR
      SAVE UP, LOW
      DATA  UP/'ABCDEFGHIJKLMNOPQRSTUVWXYZ'/
      DATA LOW/'ABCDEFGHIJKLMNOPQRSTUVWXYZ'/
      ERR = 0
      L1 = LEN(INCHAR)
      L2 = LEN(UTCHAR)
      J = 0
      UTCHAR = ' '
      DO 1 I=1,L1
      C = INCHAR(I:I)
      IF ((IN.GT.0).AND.(C.EQ.' ')) GO TO 1
      K = INDEX(LOW,C)
      IF (K.GT.0) C = UP(K:K)
      J = J + 1
      IF (J.GT.L2) GO TO 2
      UTCHAR(J:J) = C
    1 CONTINUE
    3 UT = J
      RETURN
    2 ERR = 1
      GO TO 3
      END
