      SUBROUTINE DFX011
C    CALLS SYSTEM ROUTINE (DFXMS7) TO DETECT
C    INTERACTIVE/BATCH STATUS
C    THEN SETS LOGICAL FLAG ACCORDINGLY
C    SEPARATE FUNCTION TO ENABLE USE BY OTHER PRODUCTS USING
C    DIMFILM DEVICE DRIVERS BUT NOT DOING FULL DIMFILM
C    INITIALISATION (VIA DFX006)
      INCLUDE 'dfxc12.cmn'
      CALL DFXMS7(IA)
      SYSIA = IA.NE.0
      RETURN
      END
C
C----------------------------------------------
C
