      SUBROUTINE DFX104(IN1,X1,Y1)
      LOGICAL IN, IN1
      EQUIVALENCE (N1,N1BLP)
      INCLUDE 'dfxc00.cmn'
C*CALL DFXC00S
      INCLUDE 'dfxcd0.cmn'
C*CALL DFXCD0S
      SAVE
      IN = IN1
      X = X1
      Y = Y1
C    NO1, NO2 FIRST AND LAST WORDS IN XLINE( ) OF PATTERN IDASH
C   XL UNIT LENGTH, XLDONE LENGTH DONE OF CURRENT WORD N1
      IF (IDASH.NE.0) GO TO 2
      I = 2
      IF (IN) I = 3
      XPOS = X
      YPOS = Y
      CALL DFX000(I,XPOS,YPOS,ZDUMMY,NDUMMY)
      RETURN
    2 A = X - XPOS
      B = Y - YPOS
      D = SQRT(A*A + B*B)
      IF (D.LE.0.0) RETURN
C      THIS ENSURES A ZERO LENGTH MOVE WILL NOT BE ATTEMPTED FOR A
C    BROKEN LINE PATTERN.  THE SEEMINGLY REDUNDANT ATTEMPT TO DO SO
C    IS FORCED BY MACHINE ACCURACY CHECKS IN DFX100.
      XSTEP = A/D
      YSTEP = B/D
      IF (.NOT.IN.AND.(D.GT.TL)) GO TO 18
   20 IF (D.LE.0.0) RETURN
      XL1 = XLINE(N1)
      AXL1 = ABS(XL1) - XLDONE
      IF (D-AXL1) 11,12,13
   13 IF (XL1.EQ.0.0) GO TO 15
      D = D - AXL1
      XLDONE = 0.0
      XPOS = XPOS + AXL1*XSTEP
      YPOS = YPOS + AXL1*YSTEP
   17 N1 = N1 + 1
      IF (N1.GT.NO2) N1 = NO1
   14 I = 3
      IF ((XL1.LT.0.0).OR.(.NOT.IN)) I = 2
      CALL DFX000(I,XPOS,YPOS,ZDUMMY,NDUMMY)
      GO TO 20
   11 XLDONE = XLDONE + D
      D = 0.0
      XPOS = X
      YPOS = Y
      GO TO 14
   12 XPOS = X
      YPOS = Y
      XLDONE = 0.0
      D = 0.0
      GO TO 17
   15 IF (.NOT.IN) GO TO 16
      IF (NPTTYP.LT.0) THEN
                       CALL DFX109(XPOS,YPOS)
                       ELSE
                       CALL DFX000(1,XPOS,YPOS,ZDUMMY,NPTTYP)
      ENDIF
   16 N1 = N1 + 1
      IF (N1.GT.NO2) N1 = NO1
      XLDONE = 0.0
      GO TO 20
   18 J = D/TL
      D1 = J*TL
C   SOME COMPILERS PERFORM I=X/Y AS I=X*(1./Y)
C   THIS MAY YIELD AN INTEGER RESULT THAT IS 1 TOO SMALL
C   THE FOLLOWING LINE IS TO REMEDY THAT SITUATION
C   (SPECIFICALLY CFT77)
C   THIS IS CORRECT ONLY FOR POSITIVE D AND TL (AS HERE)
      IF ((D-D1).GE.TL) D1 = D1 + TL
      XPOS = XPOS + D1*XSTEP
      YPOS = YPOS + D1*YSTEP
      CALL DFX000(2,XPOS,YPOS,ZDUMMY,NDUMMY)
      D = D - D1
      GO TO 20
      ENTRY DFX105
      N1 = NO1
      XLDONE = 0.0
      RETURN
      END
C
C----------------------------------------------
C
