      SUBROUTINE DFX142(N,ZZ)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc04.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ZZZ = AMIN1(AMAX1(ZZ,0.0),DFX145(N))
      IF (ABS(ZZ-ZZZ).GT.DZINT) GO TO 1
    2 ZF = 0.0
      IF (ZINT0(N).NE.0.) ZF = ZZZ/ZINT0(N)
      R(N) = R0(N)*ZF
      G(N) = G0(N)*ZF
      B(N) = B0(N)*ZF
      ZINT(N) = ZZZ
      IF (ICOLPT(IRGBN).EQ.N) CALL DFX140(IRGBN)
      RETURN
    1 IF (ROUTIN(1:5).NE.'INTSY') GO TO 2
C    SKIP DIAGNOSTIC IF VIA DFX148 - SHOULD BE CHECKED ELSEWHERE
      IF (ICHECK.GT.0) WRITE(ERRREC,10) ROUTIN,ZZ,ZZZ
      CALL DFX130(0)
   10 FORMAT(1H0,'**DIMFILM WARNING**  ROUTINE ',A,' CALLED WITH INVALID
     1 INTENSITY ',1PE16.8/1H ,21X,'  (EITHER NEGATIVE OR EXCEEDS MAXIMU
     2M POSSIBLE WITH CURRENT COLOUR TRIPLET)'/1H ,21X,'INTENSITY ',
     3 1PE16.8,' USED INSTEAD')
      GO TO 2
      END
C
C----------------------------------------------
C
