      SUBROUTINE DFX106(X1,Y1)
      LOGICAL IN, DFX103
      LOGICAL IN1, IN2
      LOGICAL FIN, FIN2
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
C      PRINT *,'DFX106: ',X1,Y1
      XEND = X1
      YEND = Y1
      IF (.NOT.WCTR) GO TO 1
      XEND = X0T + X1*CALPHA - Y1*SALPHA
      YEND = Y0T + X1*SALPHA + Y1*CALPHA
    1 IN1 = XEND.EQ.XPOS
      IN2 = YEND.EQ.YPOS
      IF (IN1.AND.IN2) RETURN
      IF (IABS(ICHECK).LT.2) GO TO 10
C--- BOUNDS/WC WINDOW CHECKING PERFORMED NOW - MAY NEED AMENDING
      IN = DFX103(XEND,XB1,XB2).AND.DFX103(YEND,YB1,YB2)
      IF (.NOT.IN) GO TO 3
   10 IF (IN1) GO TO 11
      IF (IN2) GO TO 12
      IF ((XPOS.EQ.XEND).AND.(YPOS.EQ.YEND)) GO TO 5
      IN = .TRUE.
      FIN = .TRUE.
      X = XEND
      Y = YEND
      IF (.NOT.PWIND) GO TO 20
      FIN = .FALSE.
      CALL DFX100(1,XEND,YEND,IN,X,Y,FIN)
      IF (IN) GO TO 20
      CALL DFX104(IN,X,Y)
      IF (FIN) GO TO 5
      CALL DFX100(1,XEND,YEND,IN,X,Y,FIN)
      IF (.NOT.IN) GO TO 21
   20 IF (.NOT.BLNKS) GO TO 21
      FIN2 = .FALSE.
      CALL DFX100(2,X,Y,IN,XP,YP,FIN2)
      IN = .NOT.IN
      CALL DFX104(IN,XP,YP)
      IF (FIN2) GO TO 22
      CALL DFX100(2,X,Y,IN,XP,YP,FIN2)
      IN = .NOT.IN
      CALL DFX104(IN,XP,YP)
      IF (FIN2) GO TO 22
      IN = .TRUE.
   21 CALL DFX104(IN,X,Y)
   22 IF (FIN) GO TO 5
      CALL DFX104(.FALSE.,XEND,YEND)
      GO TO 5
    3 IF (IABS(ICHECK).EQ.3) GO TO 6
      IOBCNT = IOBCNT + 1
      IF (ICHECK.EQ.2) WRITE(ERRREC,4) X1,Y1,XEND,YEND,XB1,XB2,YB1,YB2
      CALL DFX130(1)
    4 FORMAT(1H0, 49H**DIMFILM WARNING** OUT OF BOUNDS DETECTED BY ON2
     1  /1H0,21X, 12HCALLED WITH ,1P2E14.5/1H0,21X, 12HTHESE BEING ,1P2E
     214.5,  30H IN USERS ORIGINAL COORDINATES/1H0,21X, 18HUSERS BOUNDS
     3WERE ,    1P4E14.5)
      GO TO 10
    6 XPOS = XEND
      YPOS = YEND
      XS = X1
      YS = Y1
      CALL DFX001('ON2',6)
   11 IF (PWIND.AND..NOT.DFX103(XPOS,XTB1,XTB2)) GO TO 13
      CALL DFX108(YEND)
      GO TO 5
   12 IF (PWIND.AND..NOT.DFX103(YPOS,YTB1,YTB2)) GO TO 13
      CALL DFX107(XEND)
      GO TO 5
   13 IN = .FALSE.
      CALL DFX104(IN,XEND,YEND)
      XPOS = XEND
      YPOS = YEND
    5 RETURN
      END
