      SUBROUTINE DFX122
C
C    **INTERNAL DIMSET FUNCTION**
C
C    DIMFILM INITIATION ROUTINE - FIRST INITIATES GKS (WHICH
C    PRESETS DIMFILM COMMON TO GKS DEFAULTS) THEN ADDS SPECIFIC
C    DIMFILM DEFAULTS WHERE THESE CONTRADICT THOSE APPLIED BY GKS.
C    MAY ONLY BE ENTERED WHEN SYSTEM CLOSED.
      INCLUDE 'params.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcbc.cmn'
      INCLUDE 'dfxcbcs.cmn'
C
C NG- OCT 2008: DEBUG
C
C      PRINT 888,SYSTEM
C 888  FORMAT(1X,'SYSTEM=',A)
C
      IF (SYSTEM.NE.'*******') GO TO 1000
C    ERRROR IF SYSTEM ALREADY DEFINED
      CALL DFXG00
C    GO INITIATE GKS (ALSO SETS DIMFILM DEFAULTS)
C    THEN SET DIMFILM SPECIFIC DEFAULTS ETC
      PREBND(1) = .TRUE.
C    DIMFILM CLIPS AT BOUNDS BY DEFAULT ON TRANSFORMATION 1
      CALL DFX0AA(1)
C    SELECT TRANSFORMATION 1
      SYSTEM = 'DIMFILM'
C    SET SYSTEM NAME
      RETURN
 1000 CALL DFX001('DIMSET',14)
      END
C
C----------------------------------------------
C
