      SUBROUTINE DFX124(X1,Y1)
C
C    **INTERNAL ON2 FUNCTION - PRESERVES INTERRUPTS**
C            (ELSE USE DFX106 DIRECTLY)
C
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      CALL DFX106(X1,Y1)
      IF (INTEND.LT.0) GO TO 1
      INTCH = INTCH + 1
      IF (INTCH.LT.INTEND) GO TO 1
C    N.B. BROKEN LINE PATTERN IS PRESERVED ACROSS INTERUPT SYMBOLS
C    INTERNALLY IN MARKER/DFX200
      CALL DFX200(IICHAR)
      INTCH = 0
    1 CONTINUE
      RETURN
      END
