      SUBROUTINE DFX120(XLEFT,XRIGHT,YLOW,YUP)
C
C    **INTERNAL BOUNDS FUNCTION**
C
      INCLUDE 'params.cmn'
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
C    MAXBET IS NUMBER OF SIMULTANEOUSLY IN-CORE ALPHABETS
C    DIMFILM CURRENTLY SUPPORTS MAXBET UP TO A MAXIMUM OF 3
      PARAMETER (MAXBET=3)
      INCLUDE 'dfxc20.cmn'
      INCLUDE 'dfxc20s.cmn'
      INCLUDE 'dfxcac.cmn'
      INCLUDE 'dfxcacs.cmn'
      INCLUDE 'dfxcba.cmn'
      INCLUDE 'dfxcbb.cmn'
      INCLUDE 'dfxcbc.cmn'
      INCLUDE 'dfxcbcs.cmn'
      WCBND1(1) = XLEFT
      WCBND1(2) = XRIGHT
      WCBND1(3) = YLOW
      WCBND1(4) = YUP
      IF ((XLEFT.GE.XRIGHT).OR.(YLOW.GE.YUP)) CALL DFX001('BOUNDS',1)
      XB1 = XLEFT
      XB2 = XRIGHT
      YB1 = YLOW
      YB2 = YUP
C    SELECT TRANSFORMATION 1
      CALL DFX0AA(1)
      PRECLP(1) = .TRUE.
      PREBLK(1) = .FALSE.
      RATIO1 = (XB2-XB1)/(YB2-YB1)
      RATIO2 = (NDCVP(2,NOTRP)-NDCVP(1,NOTRP))/(NDCVP(4,NOTRP)-
     1          NDCVP(3,NOTRP))
      IF (RATIO2.GT.RATIO1) GO TO 1
C    HERE FOR EXACT FIT OF X-RANGE
      WCWIN(1,NOTRP) = XB1
      WCWIN(2,NOTRP) = XB2
C    Y-RANGE = (XB2-XB1)/RATIO2; Y-MARGIN = .5*(YRANGE-(YB2-YB1))
      DIFF = .5*(((XB2-XB1)/RATIO2) - (YB2-YB1))
      WCWIN(3,NOTRP) = YB1 - DIFF
      WCWIN(4,NOTRP) = YB2 + DIFF
      GO TO 2
C    ELSE EXACT FIT OF Y-RANGE
    1 WCWIN(3,NOTRP) = YB1
      WCWIN(4,NOTRP) = YB2
      DIFF = .5*(((YB2-YB1)*RATIO2) - (XB2-XB1))
      WCWIN(1,NOTRP) = XB1 - DIFF
      WCWIN(2,NOTRP) = XB2 + DIFF
    2 CONTINUE
C    SET CLIPPING
C
C    PERFORM EQUIVALENT FUNCTION TO ENPANE
C
      PCLPWC(1,1) = WCBND1(1)
      PCLPWC(2,1) = WCBND1(2)
      PCLPWC(3,1) = WCBND1(3)
      PCLPWC(4,1) = WCBND1(4)
      PRECLP(1) = .FALSE.
      IF (NOTR.EQ.1) CALL DFX2AA
C
C    SET NEW BEAM/CHARACTER POSITIONS
      XPOS = XB1
      YPOS = YB1
      XS = XB1
      YS = YB1
      XSPOS = XB1
      YSPOS = YB1
C    CLEAR SHIFT/ROTATIONS
      X0T = 0.0
      Y0T = 0.0
      CALPHA = 1.0
      SALPHA = 0.0
      ALPHA = 0.0
C    RESET TRANSFORMATION 1
      CALL DFX1AA
C    POSITION BEAM
      CALL DFX111(XB1,YB1)
C    CHARACTER HEIGHT/BROKEN LINE SCALING PERFORMED IN DFX1AA
      IF (ITRDSH.NE.1) GO TO 3
      X = .01*(XB2-XB1)
      CALL DFX135(X)
    3 CONTINUE
C    CHARDEF NOT REQUIRED AS SET IN SYMTXT/SYM
      RETURN
      END
C
C----------------------------------------------
C
