      SUBROUTINE DFX109(XR,YR)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc04.cmn'
      INCLUDE 'dfxcd0.cmn'
      INCLUDE 'dfxcd0s.cmn'
      X = XR
      Y = YR
C    GET APPROPRIATE SCALE FACTOR
      SF = SFSPOT(ICOLPT(IRGBN))
      IF (SF.LE.0.0) GO TO 999
C    SAVE LINE SCALE FACTOR - AND TEMPORARILY SET TO UNITY
      SAVL = SFLIN(ICOLPT(IRGBN))
      SFLIN(ICOLPT(IRGBN)) = 1.0
C    FORCE CHANGE FLAG
      CALL DFX140(IRGBN)
      REDN = 1./SQRT(2.0)
    1 D1 = DXWCPT*SF
      D2 = D1*REDN
C    SOFTWARE SPOT IS OCTAGONAL
      CALL DFX000(2,X-D1,Y,ZDUMMY,NDUMMY)
      CALL DFX000(3,X-D2,Y+D2,ZDUMMY,NDUMMY)
      CALL DFX000(4,X,Y+D1,ZDUMMY,NDUMMY)
      CALL DFX000(4,X+D2,Y+D2,ZDUMMY,NDUMMY)
      CALL DFX000(4,X+D1,Y,ZDUMMY,NDUMMY)
      CALL DFX000(4,X+D2,Y-D2,ZDUMMY,NDUMMY)
      CALL DFX000(4,X,Y-D1,ZDUMMY,NDUMMY)
      CALL DFX000(4,X-D2,Y-D2,ZDUMMY,NDUMMY)
      CALL DFX000(4,X-D1,Y,ZDUMMY,NDUMMY)
      SF = SF - 1.0
C    MUST TEST FOR POSITIVE TO FORCE FILL OF CENTRE OF POINT
      IF (SF.GT.0.0) GO TO 1
C    RESTORE LINE SCALE FACTOR BEFORE RETURNING
      SFLIN(ICOLPT(IRGBN)) = SAVL
C    AND FORCE CHANGE FLAG
      CALL DFX140(IRGBN)
  999 CALL DFX000(2,X,Y,ZDUMMY,NDUMMY)
      RETURN
      END
