      SUBROUTINE DFX111(X,Y)
      LOGICAL IN, DFX103
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcd0.cmn'
      INCLUDE 'dfxcd0s.cmn'
C
C    DFX111 IS DIRECTLY REFERENCED ONLY BY OFF2
C
C    DIRECT REFERENCE TO OFF2 WILL DO FORCED OFF MOVE IF ANY
C    IMMEDIATE DEVICE IS ACTIVE (E.G. TO ENABLE CURSOR FOLLOWING)
      IOFF = 2
      IF (IMM) IOFF = 1
      GO TO 6
      ENTRY DFX110(X,Y)
      IOFF = 2
    6 XEND = X
      YEND = Y
      IF (.NOT.WCTR) GO TO 2
      XEND = X0T + X*CALPHA - Y*SALPHA
      YEND = Y0T + X*SALPHA + Y*CALPHA
    2 IF (IABS(ICHECK).LT.2) GO TO 1
C--- BOUNDS/WC WINDOW CHECKING PERFORMED NOW - MAY NEED AMENDING
      IN = DFX103(XEND,XB1,XB2).AND.DFX103(YEND,YB1,YB2)
      IF (.NOT.IN) GO TO 3
    1 CALL DFX105
      XPOS = XEND
      YPOS = YEND
      CALL DFX000(IOFF,XPOS,YPOS,ZDUMMY,0)
      RETURN
    3 IF (IABS(ICHECK).EQ.3) GO TO 5
      IOBCNT = IOBCNT + 1
      IF(ICHECK.EQ.2)WRITE(ERRREC,4)ROUTIN,X,Y,XEND,YEND,XB1,XB2,YB1,YB2
      CALL DFX130(1)
    4 FORMAT(1H0,'**DIMFILM WARNING** OUT OF BOUNDS DETECTED BY ',A,
     1 ' DURING OFF MOVE'/1H0,21X,'CALLED WITH ',1P2E14.5/
     2 1H0,21X,'THESE BEING ',1P2E14.5,' IN USERS ORIGINAL COORDINATES'/
     3 1H0,21X,'USERS BOUNDS WERE ',1P4E14.5)
      GO TO 1
    5 XPOS = XEND
      YPOS = YEND
      XS = X
      YS = Y
      CALL DFX001('OFF2',7)
      END
C
C----------------------------------------------
C
