      SUBROUTINE DFX130(I)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      DATA MAXWRN/100/
      DATA LSTFRM/0/,NUSFRM/0/
C    IF STARTF IS MODIFIED TO CALL FRAME THEN THE INITIALISATION
C    OF NUSFRM MUST REFLECT THIS TO GIVE CORRECT COUNT.
      IF (ICHECK.LE.I) RETURN
C    RETURN IF MESSAGE NOT OF PRINTABLE LEVEL
      NUMWRN = NUMWRN + 1
      CALL DFX005
      IF (NUMWRN.LT.MAXWRN) RETURN
C    PERMITTED NUMBER OF PRINTED WARNING MESSAGES SET AT 100
      IICHAR = NUSFRM + 1
C    THIS PASSES APPROPRIATE FRAME SEQUENCE TO DFX001(12) TO AVOID
C    RECURSIVE CALL OF DFX131(-1000)
      CALL DFX001(ROUTIN,0)
      ENTRY DFX131(I)
      IF (I.EQ.-999) GO TO 1
      IF (I.EQ.-1000) GO TO 3
      MAXWRN = I
      RETURN
    1 NUSFRM = NUSFRM + 1
C    NUSFRM IS COUNT OF USER CALLS OF FRAME - NOTE THAT THIS DOES NOT
C    INDICATE TOTAL FRAME COUNT AS REPEATS AND BANNERS ARE EXCLUDED.
      IF (NUMWRN.LE.LSTFRM) GO TO 4
      WRITE(ERRREC,2)NUSFRM
    2 FORMAT(1H0,119(1H-)/1H , 91H**DIMFILM NOTE**  THE PRECEDING DIMFIL
     1M WARNINGS WERE GENERATED DURING USER FRAME SEQUENCE ,I6/1H ,
     2   119(1H-))
      CALL DFX005
    4 LSTFRM = NUMWRN
C    LSTFRM HOLDS NUMBER OF WARNINGS PRINTED PRIOR TO LAST SEQUENCE
C    IDENTIFICATION PRINTED.
      RETURN
    3 I = NUSFRM + 1
C    IF FINIF IS MODIFIED TO CALL FRAME THEN THIS COUNT SHOULD BE
C    AMENDED.
      RETURN
      END
C
C----------------------------------------------
C
