      SUBROUTINE DFX121
C
C    **INTERNAL DIMEND FUNCTION**
C
C    CLOSE ALL OPEN/ACTIVE WORK STATIONS AND CLOSE DIMFILM/GKS
      INCLUDE 'params.cmn'
      INCLUDE 'dfxcac.cmn'
      INCLUDE 'dfxcacs.cmn'
      INCLUDE 'dfxcad.cmn'
      INCLUDE 'dfxcba.cmn'
      INCLUDE 'dfxcbd.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      EXTERNAL DFX007
C    DEACTIVATE ALL ACTIVE WORK STATIONS
      IF (NCACWS.LE.0) GO TO 2
      FATPT = 1
      NLOOP = NCACWS
C    FIX NUMBER OF PASSES THROUGH LOOP
      DO 1 I=1,NLOOP
      NWS = LACWS(1)
C    NOTE - LIST RECOMPILED ON EACH ENTRY TO DFXG05 REMOVING DEACTIVATED
C           WORK STATION; THUS ALL ACTIVE WILL CYCLE THROUGH ENTRY 1
      CALL DFXG05(NWS)
    1 IF (GKSERR.NE.0) GO TO 1000
C    GO CLOSE ALL OPEN WORK STATIONS
    2 IF (NCOPWS.LE.0) GO TO 4
      FATPT = 2
      NLOOP = NCOPWS
C    FIX NUMBER OF PASSES THROUGH LOOP
      DO 3 I=1,NLOOP
      NWS = LOPWS(1)
C    NOTE - LIST RECOMPILED ON EACH ENTRY TO DFXG03 REMOVING CLOSED W/S
      CALL DFXG03(NWS)
    3 IF (GKSERR.NE.0) GO TO 1000
    4 FATPT = 3
      CALL DFXG01
      IF (GKSERR.NE.0) GO TO 1000
C    ISSUE SEQUENCE NUMBER FOR PRECEDING DIAGNOSTICS
      CALL DFX131(-999)
      SYSTEM = '*******'
C    ROUTIN MUST BE CLEARED AT EXIT FROM DIMFILM
      ROUTIN = DASH6
      DO 5 I=1,6
    5 ERRREC(I) = '*'
C    FOR COMPLETENESS CLEAR 'JUMP' TABLE IN DFXM06
      DO 6 I=1,MSOPWS
    6 CALL DFXM06(DFX007,I)
      RETURN
 1000 CALL DFX001('DIMEND',15)
      END
