      SUBROUTINE DFX204(K,RNUMB,INUMB,FMT)
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxc04.cmn'
      INCLUDE 'dfxc14.cmn'
      CHARACTER*(*) FMT
      CHARACTER*4 IRNUM(2)
      REAL RNUMB
      INTEGER INUMB
      SAVE IRNUM
      DATA IRNUM/'RNUM','INUM'/
C    ENCODE STRING ACCORDING TO FORMAT FMT - SINGLE RECORD, MAXIMUM
C    LENGTH SUPPORTED 150 ( = STR150)
C    TRAILING BLANKS STRIPPED
      STR150 = ' '
C
C    IF FORMAT CONTAINS MULTIPLE RECORDS IT IS POSSIBLE FOR PROGRAM
C    TO BE OVERWRITTEN.  ERRNUM = 12 IN TRANSFER TO DFX001 HAS BEEN
C    RESERVED FOR THIS IF DETECTION IS POSSIBLE.
C    (WILL ONLY OCCUR IF FORMAT CONTAINS / - NOT WITHIN STRING - AND
C     I/O LIST - SINGLE VARIABLE - HAS NOT BEEN EXHAUSTED)
C
      IF (K.EQ.1) WRITE(STR150,FMT) RNUMB
      IF (K.EQ.2) WRITE(STR150,FMT) INUMB
      N = LEN(FMT)
      DO 1 I=150,1,-1
      IF (STR150(I:I).NE.' ') GO TO 2
    1 CONTINUE
      GO TO 31
C    IF BLANK STRING SKIP
    2 XP = XPASS
      XPASS = -100.
      I1CNT = IOBCNT
      CALL DFX214(STR150(1:I))
      XPASS = XP
      I2CNT = IOBCNT
      IF (I2CNT.NE.I1CNT) GO TO 30
   31 CONTINUE
      RETURN
   30 IF (ICHECK.NE.2) GO TO 32
      N = MIN(N,50)
      IF (K.EQ.1) WRITE(ERRREC,10)RNUMB,FMT(1:N)
   10 FORMAT(1H ,21X,' CALL ORIGINATED FROM A USER CALL TO RNUM, WITH -'
     1/1H ,21X,'FIRST ARGUMENT (REAL) ',1PE16.8/1H ,21X,'FORMAT COMMENCI
     2NG - ',A)
      IF (K.EQ.2) WRITE(ERRREC,11)INUMB,FMT(1:N)
   11 FORMAT(1H ,21X,' CALL ORIGINATED FROM A USER CALL TO INUM, WITH -'
     1/1H ,21X,'FIRST ARGUMENT (INTEGER) ',I10/1H ,21X,'FORMAT COMMENCIN
     2G - ',A)
   32 CONTINUE
      CALL DFX130(1)
      IF (IABS(ICHECK).NE.3) GO TO 31
      CALL DFX001(IRNUM(K),11)
C    ERRNUM = 11 USED - NOTE FOREGOING COMMENTS RE ERRNUM = 12.
      END
