      SUBROUTINE DFX201(IB,NFONT,THIS,C1)
C    MAXBET IS NUMBER OF SIMULTANEOUSLY IN-CORE ALPHABETS
C    DIMFILM CURRENTLY SUPPORTS MAXBET UP TO A MAXIMUM OF 3
      PARAMETER (MAXBET=3)
      INCLUDE 'dfxc20.cmn'
      INCLUDE 'dfxc20s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      CHARACTER*6 THIS
      CHARACTER*10 C1
      CHARACTER*24 MESS(2:5)
      SAVE MESS
      DATA MESS(2)/'WAS TRUNCATED'/
      DATA MESS(3)/'HAD EXCESS ENTRIES'/
      DATA MESS(4)/'HAD INSUFFICIENT ENTRIES'/
      DATA MESS(5)/'FAILED DURING TRANSFER'/
      CALL DFXM11(IB,NFONT,IERR,INO)
      IF (IERR.LE.-1.OR.IERR.EQ.1) GO TO 998
      CFONT(IB) = NFONT
      BETCHS(IB) = INO
      IF (IERR.EQ.0) GO TO 999
      WRITE(ERRREC,100) C1,ROUTIN,NFONT,MESS(IERR),INO
  100 FORMAT(1H0,'**DIMFILM WARNING**  POSSIBLE ERROR IN ATTEMPT TO LOAD
     1 ',A,' - ORIGINATING FROM ',A/1H ,21X,'FONT (NUMBER ',I5,') ',A/
     21H ,21X,'ONLY ',I3,' COMPLETE CHARACTERS WERE TRANSFERRED AND AVAI
     3LABLE')
      GO TO 997
  998 FATPT = NFONT
C    ERRORS 20/21 - IERR MAY ONLY BE -1 OR -2
C                   IERR +1 IS FONT NOT KNOWN
      IF (IERR.EQ.-1) CALL DFX001(THIS,20)
      FATPT2 = INO
      IF (IERR.LT.-1) CALL DFX001(THIS,21)
      WRITE(ERRREC,102) NFONT,C1,ROUTIN
  102 FORMAT(1H0,'**DIMFILM WARNING**  UNKNOWN FONT (NUMBER ',I5,') DETE
     1CTED DURING ATTEMPT TO LOAD ',A/1H ,21X,'REQUEST ORIGINATED BY ',
     2A,' - CALL IGNORED')
  997 CONTINUE
      CALL DFX130(0)
  999 RETURN
      END
