      REAL FUNCTION DFX212(ITEXT)
C
C    **INTERNAL STRING FUNCTION EQUIVALENT**
C
C    THIS FUNCTION RETURNS THE LENGTH OF TEXT STRING AT UNIT HEIGHT
C
C    NOTE - TRAILING BASELINE BLANKS ARE IGNORED AND ALLOWANCE IS
C           MADE FOR ANY INTERCHARACTER SPACING (FOR THE LAST BASELINE
C           CHARACTER) SO THE RETURNED LENGTH WILL PHYSICALLY CLEAR
C           THE PLOTTED STRING
C
      CHARACTER*(*) ITEXT
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      LENGTH = .TRUE.
      CALL DFX214(ITEXT)
      LENGTH = .FALSE.
      Z = XPASS/HT
      DFX212 = Z
      XPASS = 100.0
      RETURN
      END
C
C----------------------------------------------
C
