      SUBROUTINE DFX208(IBET,NFONT)
C
C    **INTERNAL LDABET FUNCTION**
C
C    MAXBET IS NUMBER OF SIMULTANEOUSLY IN-CORE ALPHABETS
C    DIMFILM CURRENTLY SUPPORTS MAXBET UP TO A MAXIMUM OF 3
      PARAMETER (MAXBET=3)
      INCLUDE 'dfxc20.cmn'
      INCLUDE 'dfxc20s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      CHARACTER*6 THIS
      CHARACTER*10 C1
      CHARACTER*3 C2
      SAVE C2
      DATA C2/'123'/
      THIS = 'LDABET'
      IF (IBET.LT.1.OR.IBET.GT.MAXBET) GO TO 10
      IB = IBET
      C1 = 'ALPHABET '//C2(IB:IB)
      CALL DFX201(IB,NFONT,THIS,C1)
  999 RETURN
   10 WRITE(ERRREC,101) IBET,ROUTIN,NFONT
  101 FORMAT(1H0,'**DIMFILM WARNING**  ATTEMPT TO LOAD ALPHABET SPECIFIE
     1D OUT OF RANGE ALPHABET ',I3,' DETECTED BY ',A/1H ,21X,
     2'REQUESTED FONT ',I5,' - CALL IGNORED')
      CALL DFX130(0)
      GO TO 999
      END
