      SUBROUTINE DFX300
C    THIS ROUTINE MUST BE INVOKED ON ENTRY TO ANY GRAPHICAL ROUTINE
C    WHICH USES DIMFILM PLOTTING COMMANDS - IT CANCELS ROTATIONS,
C    TEMPORARY ORIGINS ETC.
C
C    NOTE
C
C    THE GRAPHICAL/CONTOURING ROUTINES ALL OPERATE WITH RESPECT TO THE
C    CURRENT WINDOW AND ALL GRAPHICAL FUNCTIONS ASOICIATED WITH THEM
C    MUST BE BRACKETTED BY CALLS TO DFX300 AND DFX301, WHICH SAVE AND
C    RESTORE SYSTEM TRANSFORMATIONS AND OTHER GLOBAL PARAMETERS.
C    SOME OF THESE ROUTINES MODIFY THE LOCAL SHIFT/ROTATE
C    TRANSFORMATION (BY AMENDIND X0T, Y0T, ALPHA, CALPHA, SALPHA ETC)
C    HOWEVER, FOR THESE CHANGES TO BECOME EFFECTIVE WCTR MUST BE SET
C    .TRUE. AND ASSOCIATED VALUES IN (FOR EXAMPLE) XTORG,YTORG SET
C    FOR CONSISTENCY (THEY MUST BE RESTORED ON EXIT) TO GUARD AGAINST
C    RECALCULATION OF THE TRANSFORMATION BY DFX128/DFX133 (INTERNAL
C    PANE AND ROTATE FUNCTIONS).  THIS IS FORCED BY A REFERENCE TO
C    DFX137 AFTER ANY SUCH VALUES ARE CHANGED.
C    ALSO, DFX128/DFX133/DFX134 THE INTERNAL PANE/ROTATE/TMPORG
C    FUNCTIONS ACT ON THE CURRENT TRANSFORM (NOTR) EXCEPT WHERE
C    THEY ARE REFERENCED BY THEIR DIRECT USER FUNCTION (WHEN THEY
C    APPLY TO NOTR = 1 ONLY).
C    PRECLIPPING AND PWIND FLAGS ARE PRESERVED -
C    IF BLANKING IS EVER PERFORMED BY GRAPHING/CONTOURING THEN THESE TOO
C    MUST BE SAVED/RESTORED
C    THE TERMINATING DFX301 REFERENCE RESTORES THE GLOBAL SITUATION.
      INCLUDE 'dfxc01.cmn'
CDC*CALL DFXC01S
      INCLUDE 'dfxc02.cmn'
CDC*CALL DFXC02S
      INCLUDE 'dfxc00.cmn'
CDC*CALL DFXC00S
      INCLUDE 'params.cmn'
      INCLUDE 'dfxcac.cmn'
CDC*CALL DFXCACS
      INCLUDE 'dfxcbc.cmn'
CDC*CALL DFXCBCS
      INCLUDE 'dfxc13.cmn'
CDC*CALL DFXC13S
      INCLUDE 'dfxc10.cmn'
CDC*CALL DFXC10S
C    MAXBET IS NUMBER OF SIMULTANEOUSLY IN-CORE ALPHABETS
C    DIMFILM CURRENTLY SUPPORTS MAXBET UP TO A MAXIMUM OF 3
      PARAMETER (MAXBET=3)
      INCLUDE 'dfxc20.cmn'
CDC*CALL DFXC20S
      REAL SSAVE(13)
      REAL GSAVE(14)
      LOGICAL HSSAV
      LOGICAL SSYMCO
      LOGICAL SMONSP
      LOGICAL SWCTR,SWCTRN,SCLIP,SWIND
      SAVE
C    ENSURE ALL DATA SAVED IN THIS ROUTINE
      IF (CANCL) GO TO 100
C    AVOID MULTIPLE STATUS PRESERVATION BY REPEATED ENTRY
      CANCL = .TRUE.
      SSAVE(1) = X0T
      SSAVE(2) = Y0T
      SSAVE(3) = XPOS
      SSAVE(4) = YPOS
      SSAVE(5) = XS
      SSAVE(6) = YS
      SSAVE(7) = ANGL
      SSAVE(8) = ALPHA
      SSAVE(9) = CALPHA
      SSAVE(10) = SALPHA
      SSAVE(11) = HT
      SSAVE(12) = CANGL
      SSAVE(13) = SANGL
      SWCTR = WCTR
      SWCTRN = WCTRN(NOTR)
      SCLIP = PRECLP(NOTR)
      SWIND = PWIND
      GSAVE(1) = PCLPWC(1,NOTR)
      GSAVE(2) = PCLPWC(2,NOTR)
      GSAVE(3) = PCLPWC(3,NOTR)
      GSAVE(4) = PCLPWC(4,NOTR)
      GSAVE(5) = XNORG(NOTR)
      GSAVE(6) = YNORG(NOTR)
      GSAVE(7) = XTORG(NOTR)
      GSAVE(8) = YTORG(NOTR)
      GSAVE(9) = AXANG(NOTR)
      GSAVE(10) = ANGLS
      GSAVE(11) = XTB1
      GSAVE(12) = XTB2
      GSAVE(13) = YTB1
      GSAVE(14) = YTB2
C    WCTR MUST BE .TRUE. WHEN TEMPORARY ORIGINS/ROTATIONS ARE SET
C    ELSEWHERE IN GRAPHICAL ROUTINES (SEE ABOVE COMMENTS)
C    NOTE - WCTR WILL BE FORCED .TRUE. WHEN REQUIRED BY DFX137
C           OTHERWISE IT SHOULD BE .FALSE. FOR EFFICIENCY.
      WCTR = .FALSE.
      WCTRN(NOTR) = .FALSE.
      XNORG(NOTR) = 0.0
      YNORG(NOTR) = 0.0
      XTORG(NOTR) = 0.0
      YTORG(NOTR) = 0.0
      AXANG(NOTR) = 0.0
      ANGLS = 0.0
      HSSAV = HS
      HS = .TRUE.
      CANGL = 1.0
      SANGL = 0.0
      NTH = .FALSE.
      SSYMCO = SYMCO
      INTNDG = INTEND
      INTCHS = INTCH
      INTCH = 0
      X0T = 0.0
      Y0T = 0.0
      ANGL = 0.0
      ALPHA = 0.0
      SALPHA = 0.0
      CALPHA = 1.0
      SYMCO = .FALSE.
      SMONSP = MONSP
      HT = 1.0
      NBET = IBET
C    SET CHARACTER DEFINITION FOR ALPHABET NBET (N.B. NOT IBET)
      NCOX = -MHWLRU(NBET)
      NCOY = BLORU(NBET)
      CYF = HT/FLOAT(HRU(NBET))
      CXF = CYF*CEXP
      CSEP = HT*CSPACE
      CMONO = (NCOX+MHWRRU(NBET))*CXF
C    FORCE CMONO/CSEP CALCULATION FOR IBET FOR VALUE ROUTINES
      C1SEP = CSEP
      C1MONO = CMONO
      INTEND = -1
  100 RETURN
      ENTRY DFX301
C    THIS ENTRY MUST BE INVOKED ON LEAVING THOSE ROUTINES REQUIRING
C    A REFERENCE TO DFX300 ON ENTRY
C
C    MULTIPLE ENTRY TO DFX301 TO RESET STATUS IS PERMISSIBLE
C    WILL RESET TO LAST SAVED STATE - ONLY ERRONEOUS IF DFX300 NEVER
C    REFERENCED
      CANCL = .FALSE.
      X0T = SSAVE(1)
      Y0T = SSAVE(2)
      XPOS = SSAVE(3)
      YPOS = SSAVE(4)
      XS = SSAVE(5)
      YS = SSAVE(6)
      ANGL = SSAVE(7)
      ALPHA = SSAVE(8)
      CALPHA = SSAVE(9)
      SALPHA = SSAVE(10)
      HT = SSAVE(11)
      CANGL = SSAVE(12)
      SANGL = SSAVE(13)
      WCTR = SWCTR
      WCTRN(NOTR) = SWCTRN
      PRECLP(NOTR) = SCLIP
      PWIND = SWIND
      PCLPWC(1,NOTR) = GSAVE(1)
      PCLPWC(2,NOTR) = GSAVE(2)
      PCLPWC(3,NOTR) = GSAVE(3)
      PCLPWC(4,NOTR) = GSAVE(4)
      XNORG(NOTR) = GSAVE(5)
      YNORG(NOTR) = GSAVE(6)
      XTORG(NOTR) = GSAVE(7)
      YTORG(NOTR) = GSAVE(8)
      AXANG(NOTR) = GSAVE(9)
      ANGLS = GSAVE(10)
      XTB1 = GSAVE(11)
      XTB2 = GSAVE(12)
      YTB1 = GSAVE(13)
      YTB2 = GSAVE(14)
      HS = HSSAV
      NTH = .FALSE.
      SYMCO = SSYMCO
      MONSP = SMONSP
      INTEND = INTNDG
      INTCH = INTCHS
      XT = XPOS - X0T
      YT = YPOS - Y0T
      X = XT*CALPHA + YT*SALPHA
      Y = YT*CALPHA - XT*SALPHA
      ICSAVE = ICHECK
      ICHECK = -1
C    RESET COLOUR/INTENSITY
      CALL DFX147(1)
      CALL DFX110(X,Y)
C    N.B. AFTER "GRAPH" RETURN ALL BROKEN LINE PATTERNS RECOMMENCE
C    FROM BEGINNING, TEXT STRINGS RESUME WITH INITIAL FEATURES SET
      ICHECK = ICSAVE
      RETURN
      END
