      SUBROUTINE DFX310(ITEXT,I1,LEFT)
C --- NG: THIS OUTPUTS GRAPH LABELS (NOT VALUES).
      CHARACTER*(*) ITEXT
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc06.cmn'
      LOGICAL LEFT
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
C      PRINT *,'DFX310  [',ITEXT,']'
      I = I1
      XD = XTB2 - XTB1
      YD = YTB2 - YTB1
      ZS = DFX212(ITEXT)
      IF (ZS.LE.0.0) GO TO 5
      CALL DFX300
      GO TO (1,2),I
C    IF COMMON FACTOR AND LABEL TOO LONG TO USE ALL AVAILABLE LENGTH
C    THEY MAY NOT BOTH BE AT SAME LEVEL.  GENERALLY A SYMMETRY OF
C    SPACES IS PERFORMED ON LEFT/RIGHT OR TOP/BOTTOM FOR CAPTIONS
C    BY ADDITION/SUBTRACTION OF SH AS NECESSARY.  THE COMMON FACTOR
C    ALWAYS APPEARS AT SAME LEVEL.
    1 ZL = DC12*XD
      DYD = DC10*YD
C   IF WISH TO FORCE CENTRED IN AVAILABLE HEIGHT FORCE MODE = 0
C   AT PRESENT LOWER X-LABEL AT TOP OF AVAILABLE SPACE
C   AND UPPER X-LABEL AT BOTTOM OF AVAILABLE SPACE
      IF (LEFT) MODE = 2
      IF (.NOT.LEFT) MODE = 1
      CALL DFX216(ITEXT,ZL,DYD,X,Y,H,MODE)
      X = XTB1 + .5*(XD-ZL) + X
      IF (LEFT) THEN
          Y = YTB1 + DC13*YD + Y
      ELSE
          Y = YTB2 - (DC13+DC10)*YD + Y
      ENDIF
    6 HT = H
      CALL DFX110(X,Y)
      CALL DFX214(ITEXT)
      CALL DFX301
    5 RETURN
    2 ZL = DC12*YD
      DXD = DC10*XD
C   IF WISH TO FORCE CENTRED IN AVAILABLE HEIGHT FORCE MODE = 0
C   AT PRESENT LEFT Y-LABEL AT BOTTOM OF AVAILABLE SPACE
C   AND RIGHT Y-LABEL AT TOP OF AVAILABLE SPACE
      IF (LEFT) MODE = 1
      IF (.NOT.LEFT) MODE = 2
C   NOTE - X AND Y TRANSPOSED IN THIS CALL TO DFX216 (Y-LABELS)
      CALL DFX216(ITEXT,ZL,DXD,Y,X,H,MODE)
      Y = YTB1 + .5*(YD-ZL) + Y
      IF (LEFT) THEN
          X = XTB1 + (DC3+DC10)*XD + X
       ELSE
C         NG- ADDED 2.0 TO MOVE RIGHT LABEL AWAY FROM EDGE.
C         THIS MAY BE ANOTHER SIDE EFFECT OF CHANGING FONTS
C         TO HERSHEY. BUT SEE ALSO UTITLE COMMENT.
          X = XTB2 - 2.0*DC3*YD + X
      ENDIF
      ANGL = 90.0
      CANGL = 0.0
      SANGL = 1.0
      GO TO 6
      END
