      REAL FUNCTION DFX302(S)
C    THIS FUNCTION IS USED TO OBTAIN THE CORRECT CHARACTERISTIC
C    OF A LOGARITHM (BASE 10) WHICH MAY BE NEGATIVE
C    SOME ALLOWANCE (.001) IS MADE FOR ROUNDING ERRORS
      S1 = S + .001
C    THIS FORCES TO HIGHER INTEGRAL PART
C    (IF WITHIN .001)  NORMAL CALL IS FOR EXACT CASE +OR- N.0000
      IF (S1.LT.0.0) S1 = S1 - 1.0
      S1 = AINT(S1)
      DFX302 = S1
      RETURN
      END
