      SUBROUTINE DFX500(X0,Y0,R1,THETA1,THETA2,ARC)
      LOGICAL ARC
C    ARC = .TRUE. INDICATES ARC REFERENCE
C        = .FALSE. INDICATES WHOLE CIRCLE REFERENCE (THETAS IGNORED)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc03.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcd0.cmn'
      INCLUDE 'dfxcd0s.cmn'
      LOGICAL WCHOLD
      R = R1
      IF (R.LE.0.0) GO TO 10
      IF (ARC) GO TO 5
      DEG = 0.0
C    NOTE RELEVANCE OF COMMENTS IN ELLIPSE ROUTINES.
    4 XFIRST = R*COS(DEG)
      XLAST = XFIRST
      YFIRST = R*SIN(DEG)
      YLAST = YFIRST
      DEGS = TWOPI
      IF (THETA2.LT.THETA1) DEGS = -TWOPI
      GO TO 1
    5 TA1 = THETA1*ANGCON(1,ANGRP(3))
      DEG = AMOD(TA1,360.0)
      DEGS = THETA2 - THETA1
      DEGS = DEGS*ANGCON(1,ANGRP(3))
      IF (ABS(DEGS).GE.TWOPI) GO TO 4
      IF (DEGS.EQ.0.0) GO TO 99
      DEGEND = DEG + DEGS
      XFIRST = R*COS(DEG)
      YFIRST = R*SIN(DEG)
      XLAST = R*COS(DEGEND)
      YLAST = R*SIN(DEGEND)
    1 X0R = X0*CALPHA - Y0*SALPHA
      Y0R = X0*SALPHA + Y0*CALPHA
      X0TS = X0T
      Y0TS = Y0T
      WCHOLD = WCTR
      XP = XPOS
      YP = YPOS
      CALL DFX000(200,XSAVE,YSAVE,ZDUMMY,0)
      ICSAVE = ICHECK
      IF (ICHECK.EQ.2) ICHECK = -2
      I1CNT = IOBCNT
      X0T = X0T + X0R
      Y0T = Y0T + Y0R
      WCTR = .TRUE.
      CALL DFX110(XFIRST,YFIRST)
      I2 = INT(ABS(DEGS)/ANGSTP)
      IF (I2.EQ.0) GO TO 6
      COSTHT = XFIRST
      SINTHT = YFIRST
      COSANG = COS(ANGSTP)
      SINANG = SIN(ANGSTP)
C    ENSURE CORRECT DIRECTION OF PLOT
      IF (DEGS.LT.0.0) SINANG = -SINANG
      DO 2 I=1,I2
      COST = COSTHT*COSANG - SINTHT*SINANG
      SINTHT = SINTHT*COSANG + COSTHT*SINANG
      COSTHT = COST
    2 CALL DFX124(COSTHT,SINTHT)
    6 CALL DFX124(XLAST,YLAST)
      CALL DFX000(200,XSAVE,YSAVE,ZDUMMY,1)
      X0T = X0TS
      Y0T = Y0TS
      WCTR = WCHOLD
      XPOS = XP
      YPOS = YP
      I2CNT = IOBCNT
      ICHECK = ICSAVE
      IF (I2CNT.EQ.I1CNT) GO TO 99
      IF (ICHECK.EQ.2) WRITE(ERRREC,20)ROUTIN,R1,X0,Y0
      CALL DFX130(1)
   20 FORMAT(1H0,'**DIMFILM WARNING**  OUT OF BOUNDS DETECTED DURING CAL
     1L OF ',A/1H ,21X,'RADIUS - ',1PE16.8,' CENTRED AT (',E16.8,
     2',',E16.8,')')
      GO TO 99
   10 IF (R.LT.0.0) GO TO 12
C    HERE FOR POINT
      CALL DFX129(X0,Y0)
      IF (ICHECK.GT.0) WRITE(ERRREC,11)ROUTIN,X0,Y0
   11 FORMAT(1H0,'**DIMFILM WARNING**  ZERO RADIUS RESULTED IN CENTRAL P
     1OINT PLOT - DETECTED IN CALL OF ',A/1H ,21X,
     2 'CENTRED AT (',1PE16.8,',',E16.8,')')
      CALL DFX130(0)
      GO TO 99
   12 IF (ICHECK.GT.0) WRITE(ERRREC,13)R,X0,Y0,ROUTIN
   13 FORMAT(1H0,'**DIMFILM WARNING**  NEGATIVE RADIUS (',1PE16.8,
     1') WITH CENTRE (',E16.8,',',E16.8,') IN CALL OF ',A/1H ,21X,
     2'CALL IGNORED')
      CALL DFX130(0)
   99 CONTINUE
      RETURN
      END
C
C----------------------------------------------
C
