      SUBROUTINE DFX502(I,XINS)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcd0.cmn'
      INCLUDE 'dfxcd0s.cmn'
      CHARACTER*6 C(3)
      DATA C/'BOUNDS','  PANE',' BLANK'/
      IF (I.EQ.1) THEN
C    MARGIN RELATIVE TO BOUNDS
             XX1 = XB1
             XX2 = XB2
             YY1 = YB1
             YY2 = YB2
      ELSEIF (I.EQ.2) THEN
C    MARGIN RELATIVE TO PANE
             XX1 = XTB1
             XX2 = XTB2
             YY1 = YTB1
             YY2 = YTB2
      ELSEIF (I.EQ.3) THEN
C    MARGIN RELATIVE TO BLANK
             XX1 = XBB1
             XX2 = XBB2
             YY1 = YBB1
             YY2 = YBB2
      ENDIF
      XIN = XINS
      IF (XIN.LT.0.0) GO TO 1
      D = AMIN1(XX2-XX1,YY2-YY1)
      IF ((2.*XIN).GE.D) GO TO 1
      CALL DFX147(3)
      X1 = XX1 + XIN
      X2 = XX2 - XIN
      Y1 = YY1 + XIN
      Y2 = YY2 - XIN
      CALL DFX000(200,XSAVE,YSAVE,ZDUMMY,0)
      CALL DFX000(1,X1,Y1,ZDUMMY,0)
      CALL DFX000(4,X2,Y1,ZDUMMY,NDUMMY)
      CALL DFX000(4,X2,Y2,ZDUMMY,NDUMMY)
      CALL DFX000(4,X1,Y2,ZDUMMY,NDUMMY)
      CALL DFX000(4,X1,Y1,ZDUMMY,NDUMMY)
      CALL DFX000(200,XSAVE,YSAVE,ZDUMMY,1)
      CALL DFX147(1)
   99 CONTINUE
      RETURN
    1 IF (ICHECK.GT.0) WRITE(ERRREC,3) XIN,ROUTIN,C(I),XX1,XX2,YY1,YY2
      CALL DFX130(0)
    3 FORMAT(1H0,'**DIMFILM WARNING**  ILLEGAL ARGUMENT ',1PE14.5,
     1' IN CALL TO ',A/
     1 1H ,21X,'ARGUMENT IS NEGATIVE OR EXCEEDS HALF THE DIFFERENCE BETW
     2EEN X- OR Y-BOUNDARY LIMITS'/1H ,21X,A,' LIMITS ARE ',
     3  1P4E14.5/1H ,21X,'CALL IGNORED')
      GO TO 99
      END
