      SUBROUTINE DIMSET
C    DIMFILM INITIATION ROUTINE - FIRST INITIATES GKS (WHICH
C    PRESETS DIMFILM COMMON TO GKS DEFAULTS) THEN ADDS SPECIFIC
C    DIMFILM DEFAULTS WHERE THESE CONTRADICT THOSE APPLIED BY GKS.
C    MAY ONLY BE ENTERED WHEN SYSTEM CLOSED.
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'DIMSET'
      CALL DFX122
      ROUTIN = STARS6
      RETURN
      END
