      SUBROUTINE DSVGCL
C --- -----------------------------------------------------------------
C
C --- THIS IS THE DEVICE SELECTION ROUTINE FOR COLOUR SVG OUTPUT.
C --- IT IS BASED ON JOHN GILBERT'S TEMPLATE DEVICE NOMINATION ROUTINE.
C
C --- NICK GLAZZARD 2022. NO COPYRIGHT.
C
C --- COMMON BLOCKS.
C
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcbd.cmn'
C
C --- DECLARE THE ACTION ROUTINE DFXD01 TO BE EXTERNAL, SO WE CAN
C --- PASS IT DOWN TO DFX ROUTINES.
C
      EXTERNAL DFXD05
C
C --- SKIP MOST OF THE CODE IF THIS IS AN INDIRECT REFERENCE (I.E.,
C --- AN INTERNAL DIMFILM REFERENCE).
C
      IF( (ROUTIN.NE.STARS6) .AND. (ROUTIN.NE.DASH6) ) GO TO 1
C
C --- IT'S A DIRECT USER CALL. OPEN DIMFILM AND SET UP THE DEVICE.
C
      ROUTIN = 'DSVGCL'
C
C      PRINT 100,1
C  100  FORMAT(1X,'AT ',I3)
      CALL DFX122
C      PRINT 100,2
      CALL DFXG02( 05, 0, DFXD05 )
C      PRINT 100,3
      IF (GKSERR.NE.0) GO TO 98
C      PRINT 100,4
C
      CALL DFXG04( 05 )
C      PRINT 100,5
      IF( GKSERR .NE. 0 ) GO TO 98
C      PRINT 100,6
C
C --- ACTIVATE THE WORKSTATION.
C
      CALL DFX5AA( 05, DCXSIZ, DCYSIZ )
C      PRINT 100,7
      CALL DFXG55( 05, 0., DCXSIZ, 0., DCYSIZ )
C      PRINT 100,8
      FRAC = 1.0 / ( AMAX1(DCXSIZ,DCYSIZ) )
C      PRINT 100,9
      DCXFR = DCXSIZ * FRAC
      DCYFR = DCYSIZ * FRAC
C      PRINT 100,10
      CALL DFXG54( 05, 0., DCXFR, 0., DCYFR )
C      PRINT 100,11
      CALL DFXG50( 05, 0., DCXFR, 0., DCYFR )
C      PRINT 100,12
      CALL DFX120( 0., DCXSIZ, 0., DCYSIZ )
C      PRINT 100,13
      GO TO 99
C
C --- NOW DO AN INDIRECT INTERNAL WORKSTATION OPEN.
C --- DIMFILM CAN ONLY RETURN GKS ERRORS 21, 24 AND 26.
C
    1 CONTINUE
C      PRINT 100,14
      CALL DFXG02( NWS, NCON, DFXD05 )
C      PRINT 100,15
      IF( GKSERR .EQ. 0 ) GO TO 99
C      PRINT 100,16
C
   98 CONTINUE
C      PRINT 100,17
      CALL DFX001( 'DSVGCL', 16 )
   99 CONTINUE
C      PRINT 100,18
      IF( IMM ) CALL DFX000( -6, DUMMY, DUMMY, DUMMY, NDUMMY )
C      PRINT 100,19
C
C --- TIDY UP AND RETURN.
C
      IF( ROUTIN .EQ. 'DSVGCL' ) ROUTIN = STARS6
C
C      PRINT 100,20
      RETURN
      END
