      SUBROUTINE DTEK4K
C --- -----------------------------------------------------------------
C
C --- THIS IS THE DEVICE SELECTION ROUTINE FOR TEK 4010 OUTPUT.
C --- IT IS BASED ON JOHN GILBERT'S TEMPLATE DEVICE NOMINATION ROUTINE.
C
C --- FURTHER MODS. NICK GLAZZARD 2013. NO COPYRIGHT.
C
C --- COMMON BLOCKS.
C
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcbd.cmn'
C
C --- DECLARE THE ACTION ROUTINE DFXD04 TO BE EXTERNAL, SO WE CAN
C --- PASS IT DOWN TO DFX ROUTINES.
C
      EXTERNAL DFXD04
C
C --- SKIP MOST OF THE CODE IF THIS IS AN INDIRECT REFERENCE (I.E.,
C --- AN INTERNAL DIMFILM REFERENCE).
C
      IF( (ROUTIN.NE.STARS6) .AND. (ROUTIN.NE.DASH6) ) GO TO 1
C
C --- IT'S A DIRECT USER CALL. OPEN DIMFILM AND SET UP THE DEVICE.
C
      ROUTIN = 'DTEK4K'
C
C --- TURN OFF NON-FATAL ERROR MESSAGES AS
C --- THESE CAUSE PROBLEMS WITH DTEK4K
C
      IEFILE = -2
C
      CALL DFX122
      CALL DFXG02( 04, 0, DFXD04 )
      IF (GKSERR.NE.0) GO TO 98
C
      CALL DFXG04( 04 )
      IF( GKSERR .NE. 0 ) GO TO 98
C
C --- ACTIVATE THE WORKSTATION.
C
      CALL DFX5AA( 04, DCXSIZ, DCYSIZ )
      CALL DFXG55( 04, 0., DCXSIZ, 0., DCYSIZ )
C      FRAC = 1.0 / ( AMAX1(DCXSIZ,DCYSIZ) )
C      DCXFR = DCXSIZ * FRAC
C      DCYFR = DCYSIZ * FRAC
      DCXFR = 1.0
      DCYFR = DCYSIZ / DCXSIZ
      CALL DFXG54( 04, 0., DCXFR, 0., DCYFR )
C
C --- N.B. 1ST ARG TO DFXG50 IS TRANSFORMATION NUMBER *NOT*
C --- WORKSTATION/DEVICE NUMBER.
C
      CALL DFXG50( 1, 0., DCXFR, 0., DCYFR )
      CALL DFX120( 0., DCXSIZ, 0., DCYSIZ )
      GO TO 99
C
C --- NOW DO AN INDIRECT INTERNAL WORKSTATION OPEN.
C --- DIMFILM CAN ONLY RETURN GKS ERRORS 21, 24 AND 26.
C
    1 CONTINUE
      CALL DFXG02( NWS, NCON, DFXD04 )
      IF( GKSERR .EQ. 0 ) GO TO 99
C
   98 CONTINUE
      CALL DFX001( 'DTEK4K', 16 )
   99 CONTINUE
      IF( IMM ) CALL DFX000( -6, DUMMY, DUMMY, DUMMY, NDUMMY )
C --- TIDY UP AND RETURN.
C
      IF( ROUTIN .EQ. 'DTEK4K' ) ROUTIN = STARS6
C
      RETURN
      END
