      SUBROUTINE EDGES(LKJI,ITICK)
C    PARAMETER LKJI IS A FOUR DIGIT INTEGER, EACH DIGIT TAKING THE VALUE
C    1 OR 0, AND CORRESPONDING TO ONE SIDE OF THE GRAPH FRAME.
C    1 INDICATES THAT THE RELEVANT SIDE IS PLOTTED, 0 IT IS NOT PLOTTED.
C    CORRESPONDENCE BETWEEN DIGIT AND SIDE POSITION IS -
C    I LOWEST SIDE
C    J LEFT HAND SIDE
C    K HIGHEST SIDE
C    L RIGHT HAND SIDE
C    TICKS WILL BE PLACED AT OPEN ENDS OF SIDES ACCORDING TO ITICK
C    ITICK = +1  INWARD TICKS
C    ITICK = -1  OUTWARD TICK
C    ITICK =  2  IN/OUT DOUBLE TICK
C    ITICK =  0  OR OTHER VALUES, NO TICKING
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc02.cmn'
      INCLUDE 'dfxc02s.cmn'
      INCLUDE 'dfxc06.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      LOGICAL S1,S2,S3,S4
      ROUTIN = 'EDGES'
      DX = XTB2 - XTB1
      DY = YTB2 - YTB1
      TIK = TC1*AMIN1(DX,DY)
      DDX = DX*DC2
      DX = DX*DC1
      DDY = DY*DC2
      DY = DY*DC1
      X = XTB2 - DDX
      Y = YTB1 + DDY
      CALL DFX300
C    SET COLOUR/INTENSITY
      CALL DFX147(3)
      CALL DFX110(X,Y)
      IDIG1 = LKJI/1000
      IDIG2 = LKJI - IDIG1*1000
      S4 = IDIG1.NE.0
      Y = Y + DY
      IF (S4) CALL DFX106(X,Y)
      IF (.NOT.S4) CALL DFX110(X,Y)
      IDIG1 = IDIG2/100
      IDIG2 = IDIG2 - IDIG1*100
      S3 = IDIG1.NE.0
      X = X - DX
      IF (S3) CALL DFX106(X,Y)
      IF (.NOT.S3) CALL DFX110(X,Y)
      IDIG1 = IDIG2/10
      IDIG2 = IDIG2 - IDIG1*10
      S2 = IDIG1.NE.0
      Y = Y - DY
      IF (S2) CALL DFX106(X,Y)
      IF (.NOT.S2) CALL DFX110(X,Y)
      X = X + DX
      S1 = IDIG2.NE.0
      IF (S1) CALL DFX106(X,Y)
      IF (.NOT.S1) CALL DFX110(X,Y)
      IF (ITICK.EQ.0.OR.IABS(ITICK).GT.2.OR.ITICK.EQ.-2) GO TO 1
      TIK1 = 0.0
      TIK2 = 0.0
      IF (ITICK.NE.1) TIK1 = -TIK
      IF (ITICK.NE.-1) TIK2 = TIK
      CALL DFX305(X,Y,S1,S4,TIK1,TIK2,-TIK1,-TIK2)
      Y = Y + DY
      CALL DFX305(X,Y,S3,S4,-TIK1,-TIK2,-TIK1,-TIK2)
      X = X - DX
      CALL DFX305(X,Y,S3,S2,-TIK1,-TIK2,TIK1,TIK2)
      Y = Y - DY
      CALL DFX305(X,Y,S1,S2,TIK1,TIK2,TIK1,TIK2)
    1 CALL DFX301
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
      END
C
C----------------------------------------------
C
