      SUBROUTINE ELARC2(XF,YF,E,SLR,PHI1,PHI2,PSI)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc03.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
C    NOTE ANGLES PHI1, PHI2 ARE IN RADIANS...PSI IS IN DEGREES
C   (ACTUALLY ANG GROUPS 2 AND 3, RESPECTIVELY)
      ROUTIN = 'ELARC2'
      CALL DFX501(XF,YF,E,SLR,PHI1,PHI2,PSI,2,.TRUE.)
C    PENULTIMATE ARGUMENT IS ELLIPSE DEFINITION TYPE
C    FINAL ARGUMENT (LOGICAL) FLAGS AS ARC REFERENCE
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
      END
