      SUBROUTINE ELARC1(X0,Y0,A,B,THETA1,THETA2,PSI2)
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'ELARC1'
      CALL DFX501(X0,Y0,A,B,THETA1,THETA2,PSI2,1,.TRUE.)
C    PENULTIMATE ARGUMENT IS ELLIPSE DEFINITION TYPE
C    FINAL ARGUMENT (LOGICAL) FLAGS AS ARC REFERENCE
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
      END
