      SUBROUTINE ELLIPS(X0,Y0,A,B,PSI)
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'ELLIPS'
      CALL DFX501(X0,Y0,A,B,0.0,360.0,PSI,1,.FALSE.)
C    PARAMETER 6  USED BY DFX501 FOR DIRECTION ONLY
C                                - DEGREES USED HERE DESCRIPTIVELY
C    PENULTIMATE ARGUMENT IS ELLIPSE DEFINITION TYPE
C    FINAL ARGUMENT (LOGICAL) FLAGS AS ARC REFERENCE
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
      END
C
C----------------------------------------------
C
