      SUBROUTINE FNPLOT(FN)
      LOGICAL OUT
      LOGICAL ZERO
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcd0.cmn'
      INCLUDE 'dfxcd0s.cmn'
      ROUTIN = 'FNPLOT'
      X1 = (XTB1-X0T)*CALPHA + (YTB1-Y0T)*SALPHA
      X2 = (XTB2-X0T)*CALPHA + (YTB1-Y0T)*SALPHA
      X3 = (XTB1-X0T)*CALPHA + (YTB2-Y0T)*SALPHA
      X4 = (XTB2-X0T)*CALPHA + (YTB2-Y0T)*SALPHA
      Y1 = (YTB1-Y0T)*CALPHA - (XTB1-X0T)*SALPHA
      Y2 = (YTB1-Y0T)*CALPHA - (XTB2-X0T)*SALPHA
      Y3 = (YTB2-Y0T)*CALPHA - (XTB1-X0T)*SALPHA
      Y4 = (YTB2-Y0T)*CALPHA - (XTB2-X0T)*SALPHA
      OUT = .TRUE.
      ZERO = .FALSE.
      XP1 = AMIN1(X1,X2,X3,X4)
      YP1 = AMIN1(Y1,Y2,Y3,Y4)
      XP2 = AMAX1(X1,X2,X3,X4)
      YP2 = AMAX1(Y1,Y2,Y3,Y4)
      ICSAVE = ICHECK
      XPS = XPOS
      YPS = YPOS
      CALL DFX000(200,XSAVE,YSAVE,ZDUMMY,0)
      I1CNT = IOBCNT
      IF (ICHECK.GT.1) ICHECK = -2
      X = XP1
      Y = FN(X,DX)
      IF (DX.EQ.0.0) ZERO = .TRUE.
      CALL DFX110(X,Y)
      IF (IDASH.NE.0) GO TO 1
      IF (Y.LE.YP2.AND.Y.GE.YP1) OUT = .FALSE.
    3 XP = X
      YP = Y
      X = X + DX
      IF (X.GT.XP2) GO TO 5
      IF (X.LT.XP1) GO TO 4
      Y = FN(X,DX)
      IF (DX.EQ.0.0.AND.ZERO) GO TO 7
      ZERO = DX.EQ.0.0
      IF (Y.GT.YP2.OR.Y.LT.YP1) GO TO 2
      IF (OUT) CALL DFX110(XP,YP)
      OUT = .FALSE.
      CALL DFX124(X,Y)
      GO TO 3
    2 IF (OUT) GO TO 3
      CALL DFX124(X,Y)
      OUT = .TRUE.
      GO TO 3
    1 X = X + DX
      IF (X.GT.XP2) GO TO 5
      IF (X.LT.XP1) GO TO 4
      Y = FN(X,DX)
      IF (DX.EQ.0.0.AND.ZERO) GO TO 7
      ZERO = DX.EQ.0.0
      CALL DFX124(X,Y)
      GO TO 1
    5 X = XP2
      GO TO 6
    4 X = XP1
    6 Y = FN(X,DX)
      CALL DFX124(X,Y)
    7 ICHECK = ICSAVE
      I2CNT = IOBCNT
      CALL DFX000(200,XSAVE,YSAVE,ZDUMMY,1)
      XPOS = XPS
      YPOS = YPS
      IF (I2CNT.EQ.I1CNT) GO TO 99
      IF (ICHECK.GT.1) WRITE(ERRREC,10)
   10 FORMAT(1H0,'**DIMFILM WARNING**  OUT BOUNDS DETECTED BY FNPLOT')
      CALL DFX130(1)
   99 CONTINUE
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
      END
