      SUBROUTINE GRAPHF(FN)
      REAL SAVE(4)
      LOGICAL ZERO
      INCLUDE 'dfxc06.cmn'
      INCLUDE 'dfxc02.cmn'
      INCLUDE 'dfxc02s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      CHARACTER*1 C
      EXTERNAL DFX303
      EXTERNAL FN
      INTRINSIC ALOG10
      ROUTIN = 'GRAPHF'
      ZERO = .FALSE.
      C = 'X'
      IF (XGL.EQ.XGR) GO TO 1
      IF (XTYPE.EQ.4) GO TO 2
      C = 'Y'
      IF (YGL.EQ.YGU) GO TO 1
      IF (YTYPE.EQ.4) GO TO 2
      CALL DFX300
      ICSAVE = ICHECK
      IF (XTYPE.NE.1.OR.YTYPE.NE.1) GO TO 20
      IF (ICHECK.GT.1) ICHECK = -2
C    LINEAR-LINEAR
      XD = XTB2 - XTB1
      YD = YTB2 - YTB1
      DDX = DC2*XD
      DDY = DC2*YD
      SAVE(1) = XTB1
      SAVE(2) = XTB2
      SAVE(3) = YTB1
      SAVE(4) = YTB2
      X1 = XTB1 + DDX
      X2 = XTB2 - DDX
      Y1 = YTB1 + DDY
      Y2 = YTB2 - DDY
      CALL DFX128(X1,X2,Y1,Y2)
      S1 = (DC1*XD)/(XGR-XGL)
      S2 = (DC1*YD)/(YGU-YGL)
      X = AMIN1(XGL,XGR)
      XSTART = AMIN1(XGL,XGR)
      XEND = AMAX1(XGL,XGR)
      Y = FN(X,DX)
      IF (DX.EQ.0.0) ZERO = .TRUE.
      XP = (X - XGL)*S1 + X1
      YP = (Y - YGL)*S2 + Y1
      CALL DFX110(XP,YP)
   10 X = X + DX
      IF (X.GT.XEND) GO TO 30
      IF (X.LT.XSTART) GO TO 31
      Y = FN(X,DX)
      IF (DX.EQ.0.0.AND.ZERO) GO TO 100
      ZERO = DX.EQ.0.0
      XP = (X - XGL)*S1 + X1
      YP = (Y - YGL)*S2 + Y1
      CALL DFX106(XP,YP)
      GO TO 10
   30 X = XEND
      GO TO 32
   31 X = XSTART
   32 Y = FN(X,DX)
      XP = (X - XGL)*S1 + X1
      YP = (Y - YGL)*S2 + Y1
      CALL DFX106(XP,YP)
  100 CALL DFX128(SAVE(1),SAVE(2),SAVE(3),SAVE(4))
   40 CALL DFX301
      ICHECK = ICSAVE
   99 CONTINUE
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
    1 IF (ICHECK.GT.0) WRITE(ERRREC,11)C
      CALL DFX130(0)
   11 FORMAT(1H0, 21H**DIMFILM WARNING**  ,A1, 54H-AXIS BOUNDS HAVE NOT
     1BEEN SET PRIOR TO CALL TO GRAPHF/1H ,21X, 12HCALL IGNORED)
      GO TO 99
    2 IF (ICHECK.GT.0) WRITE(ERRREC,12)C
      CALL DFX130(0)
   12 FORMAT(1H0, 21H**DIMFILM WARNING**  ,A1, 38H-AXIS OF TYPE MONTH FO
     1R CALL TO GRAPHF/1H ,21X, 12HCALL IGNORED)
      GO TO 99
   20 GO TO (51,52),XTYPE
   51 GO TO (50,53), YTYPE
   53 CALL DFX313(FN,DFX303,ALOG10)
      GO TO 40
   52 GO TO (54,55), YTYPE
   54 CALL DFX313(FN,ALOG10,DFX303)
      GO TO 40
   55 CALL DFX313(FN,ALOG10,ALOG10)
      GO TO 40
   50 IF (ICHECK.GT.0) WRITE(ERRREC,49) XTYPE, YTYPE
      CALL DFX130(0)
   49 FORMAT(1H0, 88H**DIMFILM WARNING**  AXIS TYPES HAVE POSSIBLY BEEN
     1OVERWRITTEN - NUMERIC VALUES ARE X - ,I6,  9H AND Y - ,I6/1H ,21X,
     2 57HCALL HAS BEEN IGNORED, RETURN MADE FROM SUBROUTINE GRAPHF)
      GO TO 40
      END
