      SUBROUTINE INQF(IPT,IOUTF,IERR)
C    IERR = 0 IF VALID CALL
C         = 1 IF IPT INVALID
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
C    MAXBET IS NUMBER OF SIMULTANEOUSLY IN-CORE ALPHABETS
C    DIMFILM CURRENTLY SUPPORTS MAXBET UP TO A MAXIMUM OF 3
      PARAMETER (MAXBET=3)
      INCLUDE 'dfxc20.cmn'
      INCLUDE 'dfxc20s.cmn'
      INTEGER IVAL(12)
      REAL RVAL(6)
      REAL CVAL(2,3)
      REAL BVAL(4,3)
      EQUIVALENCE (ICHECK,IVAL), (HT,RVAL), (XPOS,CVAL), (XB1,BVAL)
C    RETURN SIMPLE INTEGER VALUES OF FONT STATUS ACCORDING TO IPT
C    0 - MAXBET
C    1-(MAXBET+2) - NO OF CHARACTERS IN CORRESPONDING RESIDENT ALPHABET
C    10 - INITIAL TEXT ALPHABET
C 10+(1-(MAXBET+2)) - FONT NUMBER OF RESIDENT ALPHABET
      ROUTIN = 'INQF'
      IERR = 0
      IOUT = MAXBET
      IF (IPT.EQ.0) GO TO 99
      IOUT = IBET
      IF (IPT.EQ.10) GO TO 99
      IF (IPT.LT.0) GO TO 1
      IT =  1 + IPT/10
      IF (IT.GT.2) GO TO 1
      IB = IPT - 10*IT
      IF ((IB.EQ.0.).OR.(IB.GT.(MAXBET+2))) GO TO 1
      GO TO (50,51), IT
   50 IOUT = BETCHS(IB)
      GO TO 99
   51 IOUT = CFONT(IB)
   99 IOUTF = IOUT
  100 CONTINUE
      ROUTIN = STARS6
      RETURN
    1 IF (ICHECK.GT.0) WRITE(ERRREC,2) ROUTIN,IPT
      CALL DFX130(0)
    2 FORMAT(1H0,'**DIMFILM WARNING** ',A,' CALLED WITH ILLEGAL POINTER'
     1,I4,' - NO RETURNED VALUE')
      IERR = 1
C    N.B.  ONLY EVER ACCESSED BY USER
      GO TO 100
      END
