      SUBROUTINE INQI(IPT,IOUT,IERR)
C    IERR = 0 IF VALID CALL
C         = 1 IF IPT INVALID
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INTEGER IVAL(12)
      REAL RVAL(6)
      REAL CVAL(2,3)
      REAL BVAL(4,3)
      EQUIVALENCE (ICHECK,IVAL), (HT,RVAL), (XPOS,CVAL), (XB1,BVAL)
C    RETURN SIMPLE INTEGER VALUES OF STATUS ACCORDING TO IPT
C    1 - ICHECK: 2 - IEFILE; 3 - INTEND; 4 - IICHAR; 5 - NOFRMS;
C    6 - NUMWRN; 7 - ITRDSH; 8 - MKVIS; 9 - ANGRP(1); 10 - ANGRP(2);
C    11 - ANGRP(3); 12 - ANGRP(4)
      ROUTIN = 'INQI'
      IERR = 0
      IF (IPT.LT.1.OR.IPT.GT.12) GO TO 1
      IOUT = IVAL(IPT)
   99 CONTINUE
      ROUTIN = STARS6
      RETURN
    1 IF (ICHECK.GT.0) WRITE(ERRREC,2) ROUTIN,IPT
      CALL DFX130(0)
    2 FORMAT(1H0,'**DIMFILM WARNING** ',A,' CALLED WITH ILLEGAL POINTER'
     1,I4,' - NO RETURNED VALUE')
      IERR = 1
C    N.B.  ONLY EVER ACCESSED BY USER
      GO TO 99
      END
