      SUBROUTINE MARKER(IC)
C    MARKER AT CURENT COLOUR/INTENSITY
      INCLUDE 'dfxc07.cmn'
      LOGICAL IN,DFX103
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'MARKER'
C    CHECK RANGE OF ARGUMENT
      IF ((IC.LE.0).OR.(IC.GT.48)) GO TO 20
      IN = DFX103(XPOS,XB1,XB2).AND.DFX103(YPOS,YB1,YB2)
      IF (.NOT.IN.AND.(MKVIS.LT.3)) GO TO 21
      I1CNT = IOBCNT
      CALL DFX200(IC)
      I2CNT = IOBCNT
      IF (I2CNT.NE.I1CNT) GO TO 22
    1 CONTINUE
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
    2 CONTINUE
      ROUTIN = STARS6
      RETURN
   22 IF (ICHECK.EQ.2) WRITE(ERRREC,5)IC
    5 FORMAT(1H0,'**DIMFILM WARNING**  OUT OF BOUNDS DETECTED BY MARKER
     1DURING PLOT OF SYMBOL ',I2)
      CALL DFX130(1)
      IF (IABS(ICHECK).EQ.3) GO TO 10
      GO TO 1
   20 IF (ICHECK.GT.0) WRITE(ERRREC,6)IC
      CALL DFX130(0)
    6 FORMAT(1H0,'**DIMFILM WARNING**  MARKER CALLED WITH ILLEGAL ARGUME
     1NT ',I4,' CALL IGNORED')
      GO TO 2
   10 IICHAR = IC
      CALL DFX001('SYM',10)
   21 IF (IABS(ICHECK).EQ.3) GO TO 10
      IF (ICHECK.EQ.2) WRITE(ERRREC,7)XPOS,YPOS,XB1,XB2,YB1,YB2,IC
      CALL DFX130(1)
    7 FORMAT(1H0,'**DIMFILM WARNING**  OUT OF BOUNDS DETECTED BY MARKER'
     1/1H ,21X,'SYMBOL PLOT AT ',1P2E14.5,' IN USERS ORIGINAL COORDINATE
     2S'/1H ,21X,'BOUNDS WERE ',1P4E14.5/1H ,21X,'CHARACTER SPECIFIED WA
     3S ',I4)
      GO TO 2
      END
