      SUBROUTINE OWCWIN
      INCLUDE 'params.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      INCLUDE 'dfxcac.cmn'
      INCLUDE 'dfxcacs.cmn'
      INCLUDE 'dfxcba.cmn'
      ROUTIN = 'OWCWIN'
      CALL DFX147(3)
      CALL DFX000(200,XSAVE,YSAVE,DUMMY,0)
      CALL DFX000(1,WCWIN(1,NOTRP),WCWIN(3,NOTRP),DUMMY,0)
      CALL DFX000(4,WCWIN(2,NOTRP),WCWIN(3,NOTRP),DUMMY,NDUMMY)
      CALL DFX000(4,WCWIN(2,NOTRP),WCWIN(4,NOTRP),DUMMY,NDUMMY)
      CALL DFX000(4,WCWIN(1,NOTRP),WCWIN(4,NOTRP),DUMMY,NDUMMY)
      CALL DFX000(4,WCWIN(1,NOTRP),WCWIN(3,NOTRP),DUMMY,NDUMMY)
      CALL DFX000(200,XSAVE,YSAVE,DUMMY,1)
      CALL DFX147(1)
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
      END
C
C----------------------------------------------
C
