      SUBROUTINE PANE(XLEFT,XRIGHT,YLOW,YUP)
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
C PANE CHANGE 1
      ROUTIN = 'PANE'
      CALL DFX128(XLEFT,XRIGHT,YLOW,YUP)
      ROUTIN = STARS6
      RETURN
      END
