      SUBROUTINE POLFN(FN)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc06.cmn'
      INCLUDE 'dfxc02.cmn'
      INCLUDE 'dfxc02s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      REAL SAVE(4)
      LOGICAL ZERO,RRLOG
      EXTERNAL FN
      CHARACTER*5 C
      INCLUDE 'dfxc03.cmn'
      ROUTIN = 'POLFN'
      RRLOG = .FALSE.
      ZERO = .FALSE.
      IF (RTYPE.EQ.2) RRLOG = .TRUE.
      C = '    R'
      IF (RGL.EQ.RGR) GO TO 1
      IF (RRLOG.AND.RGL.LT.1.0) GO TO 2
      C = 'THETA'
      IF (THGL.EQ.THGR) GO TO 1
      CALL DFX300
      ICSAVE = ICHECK
      IF (ICHECK.GT.1) ICHECK = -2
      XD = XTB2 - XTB1
      YD = YTB2 - YTB1
      CALL DFX319
      DDX = DC2*XD
      DDY = DC2*YD
      SAVE(1) = XTB1
      SAVE(2) = XTB2
      SAVE(3) = YTB1
      SAVE(4) = YTB2
      X1 = XTB1 + DDX
      X2 = XTB2 - DDX
      Y1 = YTB1 + DDY
      Y2 = YTB2 - DDY
      CALL DFX128(X1,X2,Y1,Y2)
      THETA = THGL
      TSTART = THGL
      TEND = THGR
      T = THETA*ANGCON(2,ANGRP(2))
      R = FN(T,DTH)
      IF (DTH.EQ.0.0) ZERO = .TRUE.
      IF (RRLOG) R = ALOG10(R)
      DTH = DTH*ANGCON(1,ANGRP(2))
      XP = RXR + R*COS(THETA)*RSCALE
      YP = RYR + R*SIN(THETA)*RSCALE
      CALL DFX110(XP,YP)
   10 THETA = THETA + DTH
      IF (THETA.GT.TEND) GO TO 30
      IF (THETA.LT.TSTART) GO TO 31
      T = THETA*ANGCON(2,ANGRP(2))
      R = FN(T,DTH)
      IF (RRLOG) R = ALOG10(R)
      IF (DTH.EQ.0.0.AND.ZERO) GO TO 100
      ZERO = DTH.EQ.0.0
      DTH = DTH*ANGCON(1,ANGRP(2))
      XP = RXR + R*COS(THETA)*RSCALE
      YP = RYR + R*SIN(THETA)*RSCALE
      CALL DFX106(XP,YP)
      GO TO 10
   30 THETA = TEND
      GO TO 32
   31 THETA = TSTART
   32 T = THETA*ANGCON(2,ANGRP(2))
      R = FN(T,DTH)
      IF (RRLOG) R = ALOG10(R)
      XP = RXR + R*COS(THETA)*RSCALE
      YP = RYR + R*SIN(THETA)*RSCALE
      CALL DFX106(XP,YP)
  100 CALL DFX128(SAVE(1),SAVE(2),SAVE(3),SAVE(4))
      CALL DFX301
      ICHECK = ICSAVE
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
   99 CONTINUE
      ROUTIN = STARS6
      RETURN
    1 IF (ICHECK.GT.0) WRITE(ERRREC,11)C
   11 FORMAT(1H0,'**DIMFILM WARNING**  ',A5,'-RANGE HAS NOT BEEN SET PRI
     1OR TO CALL TO POLFN - CALL IGNORED')
      CALL DFX130(0)
      GO TO 99
    2 IF (ICHECK.GT.0) WRITE(ERRREC,12)
   12 FORMAT(1H0,'**DIMFILM WARNING**  IN CALL OF POLFN LOGARITHMIC R-VA
     1LUES HAS NON-POSITIVE PART OF RANGE'/1H ,21X,'CALL IGNORED')
      CALL DFX130(0)
      GO TO 99
      END
C
C----------------------------------------------
C
