      SUBROUTINE POLTOA(R1,THETA1,XA,YA)
      INCLUDE 'dfxc02.cmn'
      INCLUDE 'dfxc02s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc03.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'POLTOA'
      T = THETA1*ANGCON(1,ANGRP(2))
      R = R1
      IF (RTYPE.NE.2) GO TO 1
      IF (R.LT.1.0) GO TO 9
      IF (RGL.LT.1.0) GO TO 20
      R = ALOG10(R)
      GO TO 2
    1 IF (R.LT.0.0) GO TO 11
    2 CALL DFX319
      XA = RXR + R*COS(T)*RSCALE
      YA = RYR + R*SIN(T)*RSCALE
   99 CONTINUE
      ROUTIN = STARS6
      RETURN
    9 IF (ICHECK.GT.0) WRITE(ERRREC,10)R
   10 FORMAT(1H0,'**DIMFILM WARNING**  ATTEMPT TO OBTAIN COORDINATE IN P
     1OLAR PLOT WITH ILLEGAL VALUE ',E16.8,' FOR R'/
     21H ,21X,'R SHOULD NOT BE < 1.0 FOR LOGARITHMIC RADIAL SCALE'/
     31H ,21X,'CALL IGNORED')
      CALL DFX130(0)
      GO TO 99
   11 IF (ICHECK.GT.0) WRITE(ERRREC,12)R
   12 FORMAT(1H0,'**DIMFILM WARNING**  ATTEMPT TO OBTAIN COORDINATE IN P
     1OLAR PLOT WITH ILLEGAL VALUE ',E16.8,' FOR R'/
     21H ,21X,'R SHOULD NOT BE < 0.0'/
     31H ,21X,'CALL IGNORED')
      CALL DFX130(0)
      RETURN
   20 IF (ICHECK.GT.0) WRITE(ERRREC,21)
   21 FORMAT(1H0,'**DIMFILM WARNING**  ATTEMPT TO OBTAIN POLAR COORDINAT
     1E WITH LOGARITHMIC RADIALS DETECTS ILLEGAL LOWER RADIAL LIMIT < 1.
     20'/1H ,21X,'CALL IGNORED')
      CALL DFX130(0)
      GO TO 99
      END
C
C----------------------------------------------
C
