      SUBROUTINE STRAIL(ITEXT,NA,SLONG)
      CHARACTER*(*) ITEXT
C    RETURNS LENGTH OF STRING (AT UNIT HEIGHT)
C    WITH TRAILING BLANKS STRIPPED
C    SUBSEQUENT CALL TO SYMXT SHOULD BE (ITEXT(1:NA))
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'STRAIL'
      CALL DFX213(ITEXT,NA,SLONG)
      ROUTIN = STARS6
      RETURN
      END
C
C----------------------------------------------
C
