      REAL FUNCTION STRFUL(ITEXT)
C    THIS FUNCTION RETURNS THE LENGTH OF TEXT STRING AT UNIT HEIGHT
C    INCLUDING TRAILING BLANKS.
C
C    NOTE - TRAILING BASELINE BLANKS ARE INCLUDED.
C           THE INTERCHARACTER SPACING IS INCLUDED AFTER THE LAST
C           BASELINE CHARACTER (WHETHER OR NOT IT IS BLANK).
C           THIS LENGTH IS THEREFORE SUITABLE FOR PLACING A
C           CONTINUATION STRING ETC.
C
C    SEE ALSO STRING/STRAIL AND COMMENTS IN DFX214
C
      CHARACTER*(*) ITEXT
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'STRFUL'
      LENGTH = .TRUE.
      CALL DFX214(ITEXT)
      LENGTH = .FALSE.
      Z = CX/HT
      STRFUL = Z
      XPASS = 100.0
      ROUTIN = STARS6
      RETURN
      END
C
C----------------------------------------------
C
