      SUBROUTINE STRFIT(ITEXT,AVAILX,AVAILY,X,Y,H)
C
C
C    THIS SUBROUTINE RETURNS THE OFFSETS AND HEIGHT TO ENABLE THE
C    INPUT TEXT STRING TO BE MAXIMALLY CENTRED WITHIN THE BOX,
C    DEFINED BY ITS AVAILABLE X AND Y EXENTS.
C    DFX216 IS USED FOR THIS PURPOSE WITH MODE=0.
C
C    NOTE - TRAILING BASELINE BLANKS ARE IGNORED AND ALLOWANCE IS
C           MADE FOR ANY INTERCHARACTER SPACING (FOR THE LAST BASELINE
C           CHARACTER) SO THE RETURNED LENGTH WILL PHYSICALLY CLEAR
C           THE PLOTTED STRING
C
      CHARACTER*(*) ITEXT
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'STRFIT'
      CALL DFX216(ITEXT,AVAILX,AVAILY,X,Y,H,0)
      ROUTIN = STARS6
      RETURN
      END
