      REAL FUNCTION STRING(ITEXT)
C    THIS FUNCTION RETURNS THE LENGTH OF TEXT STRING AT UNIT HEIGHT
C
C    NOTE - TRAILING BASELINE BLANKS ARE IGNORED AND ALLOWANCE IS
C           MADE FOR ANY INTERCHARACTER SPACING (FOR THE LAST BASELINE
C           CHARACTER) SO THE RETURNED LENGTH WILL PHYSICALLY CLEAR
C           THE PLOTTED STRING.  I.E. LENGTH IS THAT TO INCLUDE LAST
C           NON-BLANK, WITH NO CHARACTER SEPARATION AFTER LAST BASE
C           LEVEL CHARACTER.
C
C    DUPLICATED BY INTERNAL DFX212 FUNCTION
C
      CHARACTER*(*) ITEXT
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'STRING'
      LENGTH = .TRUE.
      CALL DFX214(ITEXT)
      LENGTH = .FALSE.
      Z = XPASS/HT
      STRING = Z
      XPASS = 100.0
      ROUTIN = STARS6
      RETURN
      END
C
C----------------------------------------------
C
