      REAL FUNCTION TXTLEN(ITEXT)
C    THIS FUNCTION RETURNS THE LENGTH OF TEXT STRING AT UNIT HEIGHT
C    THIS IS THE ACTUAL LENGTH THE STRING ITEXT (COMPLETE WITH
C    TRAILING BLANKS) WOULD OCCUPY.  ALLOWANCE IS MADE FOR THE
C    INTERCHARACTER SPACING FOR THE LAST CHARACTER (IF IT IS BASELINE)
C    I.E. THIS GIVES (AT UNIT HEIGHT) THE PHYSICAL SPACE OCCUPIED BY
C    THE STRING  (SEE ALSO TXTPOS)
C
      CHARACTER*(*) ITEXT
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'TXTLEN'
      LENGTH = .TRUE.
      CALL DFX214(ITEXT)
      LENGTH = .FALSE.
      Z = CXS/HT
      TXTLEN = Z
      XPASS = 100.0
      ROUTIN = STARS6
      RETURN
      END
