      REAL FUNCTION TXTPOS(ITEXT)
C    THIS FUNCTION RETURNS THE LENGTH OF TEXT STRING AT UNIT HEIGHT
C    THIS IS THE ACTUAL LENGTH AT WHICH THE STRING (COMPLETE WITH
C    TRAILING BLANKS) WOULD BE CONTINUED, AND INCLUDES THE
C    INTERCHARACTER SPACING FOR THE LAST CHARACTER.
C    I.E. THIS GIVES (AT UNIT HEIGHT) THE POSITION AT WHICH BASELINE
C    CONTINUATION WOULD OCCUR.  (SEE ALSO TXTLEN)
C    (IT MAY BE USED TO OVERLAY A PARTICULAR BASELINE CHARACTER)
C
      CHARACTER*(*) ITEXT
      INCLUDE 'dfxc01.cmn'
      INCLUDE 'dfxc01s.cmn'
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'TXTPOS'
      LENGTH = .TRUE.
      CALL DFX214(ITEXT)
      LENGTH = .FALSE.
      Z = CX/HT
      TXTPOS = Z
      XPASS = 100.0
      ROUTIN = STARS6
      RETURN
      END
