      SUBROUTINE USEREF(STRING)
C
C    THIS ROUTINE ENABLES A USER TO PROVIDE REFERENCE INFORMATION
C    THAT MAY BE USED BY CERTAIN DEVICE DRIVERS (SPECIFICLLY
C    HARD COPY DRIVERS) TO IDENTIFY A RUN.  AT ULCC THE SYSTEM
C    ROUTINES ...MS9/6 TRY TO ACQUIRE SUCH INFORMATION FROM
C    THE SYSTEM.  UP TO 20 CHARACTERS WILL BE SAVED FOR LATER USE.
C    THIS MUST BE REFERENCED BEFORE DEVICE INITIALISATION.
C    BECAUSE DIMFILM MAY NOT HAVE BEEN INITIALISED (OTHER THAN
C    BLOCK DATA NO CHECKS ARE MADE, AND NO ERRORS CAN BE ISSUED)
C
C NOTE:  RIN/ROUT/ROUTIN ARE NOT USED/SET
C
C
C
C
      CHARACTER*(*) STRING
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      USER = STRING
      USEFLG = '*'
      RETURN
      END
