      SUBROUTINE UTITLE(TEXT)
      INCLUDE 'dfxc00.cmn'
      INCLUDE 'dfxc00s.cmn'
      INCLUDE 'dfxc06.cmn'
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      CHARACTER*(*) TEXT
      ROUTIN = 'UTITLE'
C--- NG - 11-AUG-2025. THE TITLE HAS ALWAYS BEEN TOO HIGH.
C--- USING NON-ZERO FONT BASELINES MAKES IT MOVE OFF THE TOP!
C--- GRCON PARAMETERS DO NOT SEEM ABLE TO FIX THIS.
C--- USING "2 *" DOES FIX IT. SO DO THAT FOR NOW.
      Y = YTB2 - 2*DC4*(YTB2-YTB1)
      CALL DFX328(Y,TEXT)
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
      END
