      SUBROUTINE UXALAB(ITEXT)
      CHARACTER*(*) ITEXT
      INCLUDE 'dfxc05.cmn'
      INCLUDE 'dfxc12.cmn'
      ROUTIN = 'UXALAB'
      CALL DFX330(-4,ITEXT)
      IF (IMM) CALL DFX000(-6,DUMMY,DUMMY,DUMMY,NDUMMY)
      ROUTIN = STARS6
      RETURN
      END
