      PROGRAM UPTIME(OUTPUT,TAPE6=OUTPUT)
      INTEGER IRES, ISECS, IMILLI, IDAYS, IHOURS, IMINS
      REAL FSECS
      IRES = IRTIME()
      ISECS = IRES / 1000
      IMILLI = IRES - 1000 * ISECS
      IDAYS = ISECS / (24*60*60)
      ISECS = ISECS - IDAYS * (24*60*60)
      IHOURS = ISECS / (60*60)
      ISECS = ISECS - IHOURS * (60*60)
      IMINS = ISECS / 60
      ISECS = ISECS - IMINS * 60
      FSECS = ISECS + 0.001 * IMILLI
      WRITE(6,150)IDAYS,IHOURS,IMINS,FSECS
 150  FORMAT(1X,'UPTIME =',I4,' DAYS ',I2,' HOURS ',I2,
     +' MINS ',F6.3,' SECS')
      STOP
      END
