      PROGRAM WHOAMI(OUTPUT,TAPE6=OUTPUT)
      INTEGER ICL, IUIDX
      CHARACTER*4 JSN, CHASH
      CHARACTER*7 USN
      CALL CGETJN(JSN)
      ICL = IGETUSR( USN )
      IUIDX = IGETUI()
      CALL CUHASH( IUIDX, CHASH )
      WRITE(6,155)USN(1:ICL),IUIDX,CHASH,JSN
 155  FORMAT(1X,A7,1X,O6,1X,A4,1X,A7)
      STOP
      END
