      INTEGER FUNCTION STOPEN( FNO, NAME, STATUS )
C----------------------------------------------------------(STRING)-----
C OPEN OR CREATE A FILE FOR USE BY STREAD() AND STWRITE().
C USE FNO TO REFER TO THE FILE, WHICH IS CALLED NAME. STATUS SHOULD BE
C ONE OF:  'OLD', 'NEW' OR 'UNKNOWN' TO OPEN AN OLD FILE, CREATE A NEW.
C ONE WITHOUT OVERWRITING ANY EXISTING FILE OR TO CREATE A NEW ONE,
C OVERWRITING ANY EXISTING ONE.
C ALWAYS REWIND THE FILE (BY DEFAULT IT IS NOT REWOUND).
C RETURN 0 IF OK OR AN ERROR CODE FROM NOS/FTN5 IF NOT.
C-----------------------------------------------------------------------
      IMPLICIT CHARACTER*1 (A-Z)
      INCLUDE 'stringh.cmn'
      INTEGER FNO
      CHARACTER*(*) NAME, STATUS
C----
      INTEGER IERRNO
C
      OPEN(UNIT=FNO,FILE=NAME,STATUS=STATUS,RECL=160,ERR=1,
     +     IOSTAT=IERRNO)
C
      REWIND(UNIT=FNO,IOSTAT=IERRNO,ERR=1)
      STOPEN = 0
      RETURN
C---- ERROR OPENING OR CREATING OR REWINDING THE FILE.
 1    CONTINUE
      STOPEN = IERRNO
      RETURN
      END
C
      INTEGER FUNCTION STCLOSE( FNO )
C----------------------------------------------------------(STRING)-----
C CLOSE THE FILE OPEN ON FN.
C RETURN 0 IF OK OR AN ERROR CODE FROM NOS/FTN5 IF NOT.
C-----------------------------------------------------------------------
      IMPLICIT CHARACTER*1 (A-Z)
      INCLUDE 'stringh.cmn'
      INTEGER FNO
C----
      INTEGER IERRNO
C
      CLOSE(UNIT=FNO,IOSTAT=IERRNO,ERR=1)
      STCLOSE = 0
      RETURN
 1    CONTINUE
      STCLOSE = IERRNO
      RETURN
      END
