      INTEGER FUNCTION STWRITE( AIN, FOUT )
C-------------------------------------------------(STRING)--------------
C WRITE AN ASCII CODE STRING IN AIN TO FOUT. REMOVE ANY LINE FEED (KNL)
C AT THE END. RETURN THE NUMBER OF OUTPUT CHARACTERS IF OK.
C RETURN KSTERR IF AN ERROR OCCURS.
C-----------------------------------------------------------------------
      IMPLICIT CHARACTER*1 (A-Z)
      INCLUDE 'stringh.cmn'
      INTEGER AIN(KSTDIM)
      INTEGER FOUT
C----
      CHARACTER*(KCMAX) COUT
      INTEGER LEN, NOUT
C
      INTEGER STATOC, STLEN, I
C
C---- IF THE LAST CHARACTER IS A KNL, REMOVE IT.
      LEN = STLEN(AIN)
      IF( AIN(LEN) .EQ. KNL )AIN(LEN) = KSTEND
C---- CONVERT ASCII CODE STRING TO CHARACTERS FOLLOWING 6/12 RULES.
      NOUT = STATOC(AIN, COUT)
C---- WRITE THE OUTPUT LINE.
C     WRITE(FOUT,101,ERR=1)(COUT(I:I),I=1,NOUT)
C101  FORMAT(160A1)
      WRITE(FOUT,101,ERR=1)COUT(1:NOUT)
 101  FORMAT(A)
C---- NORMAL RETURN
      STWRITE = NOUT
      RETURN
C---- END OF FILE OR ERROR ARE BOTH ERRORS HERE.
 1    CONTINUE
      STWRITE = KSTERR
      RETURN
      END
