      SUBROUTINE PSMOVE( X, Y, ON )
C --- ------------------------------------------------------------------
C
C --- THIS ROUTINE PERFORMS  MOVE' AND  DRAW' OPERATIONS.
C
      REAL INPS
      PARAMETER( INPS = 72.0 )
C
      REAL X, Y
      LOGICAL ON
C
      REAL XPS, YPS
C
      INCLUDE 'dfxpsn.cmn'
C
C --- NG- OCT 2008: CDC EMULATION ONLY.
C --- DUE TO AN ISSUE THAT ARISES SOMEWHERE IN SUBROUTINE DFX214,
C --- X AND/OR Y CAN BE INDEFINITE AT THIS POINT.
C --- NG- NOV 2008: SEVERAL THINGS WERE FOUND TO BE UNINITIALIZED.
C --- FIXES HAVE BEEN MADE. BUT BEST TO ZERO FILL CORE IN CASE
C --- THERE ARE OTHERS LURKING.
C
C      IF( LEGVAR(X) .NE. 0 .OR. LEGVAR(Y) .NE. 0 )THEN
C         RETURN
C      ENDIF
C
C --- SCALE X AND Y INTO POSTSCRIPT UNITS.
C
C      PRINT 999,X,XSIZE,XOFFST,Y,YSIZE,YOFFST
C 999  FORMAT(1X,'X=',F12.6,' XS=',F12.6,' XO=',F12.6,
C     1         ' Y=',F12.6,' YS=',F12.6,' YO=',F12.6)
C
      XPS = (X * XSIZE + XOFFST) * INPS
      YPS = (Y * YSIZE + YOFFST) * INPS
C
C --- BRANCH ACCORDING TO THE BEAM BRIGHTNESS.
C
      IF( ON ) THEN
         WRITE(LUN, 100) XPS, YPS, XPOS, YPOS
         EMPTYF = .FALSE.
      ELSE
         WRITE(LUN, 200) XPS, YPS
      END IF
C
      XPOS = XPS
      YPOS = YPS
C
C --- UPDATE THE LIMITS OF THE PLOT.
C
      IF( ON ) THEN
         IF( XPS .LT. XMIN ) XMIN = XPS
         IF( XPS .GT. XMAX ) XMAX = XPS
         IF( YPS .LT. YMIN ) YMIN = YPS
         IF( YPS .GT. YMAX ) YMAX = YPS
      END IF
C
  100 FORMAT(F12.6, 1X, F12.6, 1X, F12.6, 1X, F12.6, ' ^L')
  200 FORMAT(F12.6, 1X, F12.6, ' ^M')
      END
